import "server-only";

import {createClient} from "@supabase/supabase-js";
import {readAdminExpenses} from "@/server/agent-expenses-apps-script";
import {readAdminPayments} from "@/server/admin-payments-sheets";

export type AdminActivityCategory="ENCAISSEMENTS"|"DÉPENSES"|"QR"|"STOCKAGE"|"CAISSE"|"AGENTS";
export type AdminActivity={id:string;category:AdminActivityCategory;title:string;agency:"COO"|"FIH"|"LSHI"|"KLZ"|"TOUTES";trackingCode:string|null;occurredAt:string;amount:string|null;actor:string|null;status:string|null;description:string;source:string};
export type AdminRecentActivityResult={generatedAt:string;periodHours:24;count:number;activities:AdminActivity[];sources:Record<AdminActivityCategory,"AVAILABLE"|"UNAVAILABLE_TEMPORARILY"|"NOT_RECORDED">};
type Identity={userId:string;email:string;agency:"COO"|"FIH"|"LSHI"|"KLZ"|null};

export async function readAdminRecentActivity(identity:Identity,now=new Date()):Promise<AdminRecentActivityResult>{const since=new Date(now.getTime()-86_400_000).toISOString();const results=await Promise.all([isolated("ENCAISSEMENTS",()=>payments(since)),isolated("DÉPENSES",()=>expenses(identity,since)),isolated("QR",()=>qr(since)),isolated("STOCKAGE",()=>storage(since)),isolated("CAISSE",()=>cash(since))]);const activities=results.flatMap((result)=>result.items).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));const sources=Object.fromEntries(results.map((result)=>[result.category,result.available?"AVAILABLE":"UNAVAILABLE_TEMPORARILY"])) as AdminRecentActivityResult["sources"];sources.AGENTS="NOT_RECORDED";return{generatedAt:now.toISOString(),periodHours:24,count:activities.length,activities,sources};}
async function isolated(category:Exclude<AdminActivityCategory,"AGENTS">,read:()=>Promise<AdminActivity[]>){try{return{category,available:true,items:await withTimeout(read(),12_000)}}catch{return{category,available:false,items:[]}}}
async function payments(since:string){return (await readAdminPayments()).filter((item)=>recent(item.dateTime,since)).map((item)=>({id:`payment:${item.id}`,category:"ENCAISSEMENTS" as const,title:"Encaissement",agency:item.agenceEncaissement,trackingCode:item.codeColis,occurredAt:item.dateTime,amount:`${item.montantPaye} USD`,actor:item.agent||null,status:item.statutPaiement,description:[item.modePaiement,item.reference].filter(Boolean).join(" · ")||"Paiement enregistré",source:"Encaissements"}));}
async function expenses(identity:Identity,since:string){const result=await readAdminExpenses(identity,{dateDebut:since.slice(0,10),page:1,pageSize:100});return result.depenses.filter((item)=>recent(item.dateHeure,since)).map((item)=>({id:`expense:${item.id}`,category:"DÉPENSES" as const,title:"Dépense",agency:item.agence,trackingCode:null,occurredAt:item.dateHeure,amount:`${item.montant} ${item.devise}`,actor:item.agent||null,status:item.statut,description:item.description||item.categorie||item.observation||"Dépense enregistrée",source:"Dépenses"}));}
async function qr(since:string){const {data,error}=await client().from("qr_audit_events").select("event_id,qr_id,action,new_agency,new_tracking_code,actor_id,actor_role,actor_agency,occurred_at,new_status").gte("occurred_at",since).order("occurred_at",{ascending:false}).limit(100);if(error)throw new Error("QR_AUDIT_UNAVAILABLE");return(data??[]).map((item)=>({id:`qr:${item.event_id}`,category:"QR" as const,title:qrTitle(String(item.action)),agency:nullableAgency(item.actor_agency??item.new_agency),trackingCode:item.new_tracking_code?String(item.new_tracking_code):null,occurredAt:String(item.occurred_at),amount:null,actor:`${String(item.actor_role)} · ${String(item.actor_id)}`,status:String(item.new_status),description:`${String(item.qr_id)}${item.new_agency&&item.new_tracking_code?` · ${item.new_agency} + ${item.new_tracking_code}`:""}`,source:"Audit QR"}));}
async function storage(since:string){const {data,error}=await client().from("stockage_events").select("event_id,event_type,agency,tracking_code,weight_kg_delta,actor_name,actor_role,occurred_at").gte("occurred_at",since).order("occurred_at",{ascending:false}).limit(200);if(error)throw new Error("STORAGE_EVENTS_UNAVAILABLE");return(data??[]).map((item)=>({id:`storage:${item.event_id}`,category:"STOCKAGE" as const,title:storageTitle(String(item.event_type)),agency:agency(item.agency),trackingCode:item.tracking_code?String(item.tracking_code):null,occurredAt:String(item.occurred_at),amount:null,actor:String(item.actor_name),status:String(item.event_type),description:`Variation poids : ${Number(item.weight_kg_delta)} kg · ${String(item.actor_role)}`,source:"Stockage V2"}));}
async function cash(since:string){const {data,error}=await client().from("cash_events").select("event_id,event_type,agency,direction,amount,currency,actor_name_snapshot,occurred_at,reason").gte("occurred_at",since).order("occurred_at",{ascending:false}).limit(200);if(error)throw new Error("CASH_EVENTS_UNAVAILABLE");return(data??[]).map((item)=>({id:`cash:${item.event_id}`,category:"CAISSE" as const,title:cashTitle(String(item.event_type)),agency:agency(item.agency),trackingCode:null,occurredAt:String(item.occurred_at),amount:`${Number(item.amount)} ${String(item.currency)}`,actor:String(item.actor_name_snapshot),status:String(item.direction),description:item.reason?String(item.reason):String(item.event_type),source:"Caisse"}));}
function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(),key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)throw new Error("SERVICE_UNAVAILABLE");return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}).schema("public");}
function recent(value:string,since:string){return !Number.isNaN(Date.parse(value))&&value>=since;}
function agency(value:unknown){if(!["FIH","LSHI","KLZ"].includes(String(value)))throw new Error("INVALID_AGENCY");return value as "FIH"|"LSHI"|"KLZ";}
function nullableAgency(value:unknown):"COO"|"FIH"|"LSHI"|"KLZ"|"TOUTES"{return ["COO","FIH","LSHI","KLZ"].includes(String(value))?value as "COO"|"FIH"|"LSHI"|"KLZ":"TOUTES";}
function qrTitle(value:string){return value==="INITIAL_ASSIGNMENT"?"QR associé":value==="ADMIN_CORRECTION"?"QR corrigé":"QR révoqué";}
function storageTitle(value:string){return value.includes("ARRIVAL")||value.includes("ARRIVAGE")||value.includes("ENTREE")?"Entrée Stockage":value.includes("SORTIE")||value.includes("DELIVERY")?"Sortie Stockage":value.includes("ADJUSTMENT")?"Ajustement Admin Stockage":"Mouvement Stockage";}
function cashTitle(value:string){return value==="PAYMENT_CREDIT_RECORDED"?"Entrée Caisse":value==="EXPENSE_DEBIT_RECORDED"?"Sortie Caisse":value==="ADMIN_ADJUSTMENT_RECORDED"?"Ajustement Admin Caisse":value==="CASH_CORRECTION_RECORDED"?"Correction Caisse":"Ouverture Caisse";}
function withTimeout<T>(promise:Promise<T>,delay:number){return Promise.race([promise,new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error("SOURCE_TIMEOUT")),delay))]);}
