import "server-only";
import { createClient } from "@supabase/supabase-js";
import { recordInternalNotification } from "@/server/internal-notifications";
type Actor={userId:string;name:string};
export async function notifyForwardingDeparture(id:string,actor:Actor){const row=await read(id);return recordInternalNotification({eventKey:`FORWARDING_DEPARTED:${id}`,agency:row.origin_agency,audience:"ADMIN",type:"STORAGE_EXIT",title:"ACHEMINEMENT DÉCLENCHÉ",message:message(row,"IN_TRANSIT"),actorUserId:actor.userId,actorName:actor.name});}
export async function notifyForwardingArrival(id:string,actor:Actor){const row=await read(id);return recordInternalNotification({eventKey:`FORWARDING_ARRIVED:${id}`,agency:row.destination_agency,audience:"ADMIN",type:"STORAGE_ARRIVAL",title:"ACHEMINEMENT REÇU",message:message(row,"ARRIVAL_CONFIRMED"),actorUserId:actor.userId,actorName:actor.name});}
export async function notifyForwardingPayment(id:string,paymentRequestId:string,actor:Actor){const row=await read(id);return recordInternalNotification({eventKey:`FORWARDING_PAID:${id}:${paymentRequestId}`,agency:row.destination_agency,audience:"ADMIN",type:"PAYMENT",title:"ACHEMINEMENT PAYÉ",message:message(row,"PAID"),actorUserId:actor.userId,actorName:actor.name});}
type Row={original_tracking_code:string;origin_agency:"FIH"|"LSHI"|"KLZ";destination_agency:"FIH"|"LSHI"|"KLZ";canonical_weight_kg:number;rate_usd_per_kg:number;amount_expected:number;amount_paid:number;cash_event_id:string|null};
async function read(id:string){if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error("INVALID_FORWARDING_ID");const {data,error}=await client().from("stockage_forwardings").select("original_tracking_code,origin_agency,destination_agency,canonical_weight_kg,rate_usd_per_kg,amount_expected,amount_paid,cash_event_id").eq("forwarding_id",id).single();if(error||!data)throw new Error("FORWARDING_NOTIFICATION_SOURCE_UNAVAILABLE");return data as Row;}
function message(r:Row,state:string){return `${r.original_tracking_code} — ${r.origin_agency}→${r.destination_agency} — ${Number(r.canonical_weight_kg)} kg — ${Number(r.rate_usd_per_kg)} USD/kg — ${state==="PAID"?Number(r.amount_paid):Number(r.amount_expected)} USD — ${state}${r.cash_event_id?` — cash_event ${r.cash_event_id}`:""}`;}
function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("NOTIFICATION_SOURCE_NOT_CONFIGURED");return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}).schema("public");}
