"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArrowLeft, BarChart3, ChevronRight, CircleAlert, Landmark, LoaderCircle, PackageCheck, ReceiptText, RefreshCw, ShieldAlert, TrendingUp, WalletCards, X } from "lucide-react";

import { Container, GlassPanel } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getAdminProfile } from "@/features/agent/auth";
import { getSupabaseBrowserClient } from "@/features/agent/supabase";
import { formatWeight } from "@/lib/format-weight";

import { loadAdminBilan } from "./bilan-client";
import { BILAN_COHORT_OPTIONS, buildBilanQuery, formatBilanStatus, monthPeriod, type BilanPayload, type BilanStatus } from "./bilan-ui";

const field = "mt-2 h-11 w-full rounded-md border border-white/15 bg-white/[0.05] px-3 text-white outline-none focus:border-accent";
const agencies = ["FIH", "LSHI", "KLZ"] as const;

export function AdminBilanPage() {
  const router = useRouter(); const token = useRef("");
  const [ready, setReady] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [data, setData] = useState<BilanPayload | null>(null); const [unresolved, setUnresolved] = useState("");
  const [cohort, setCohort] = useState("AT"); const [periodMode, setPeriodMode] = useState<"MONTH" | "CUSTOM">("MONTH");
  const [periodMonth, setPeriodMonth] = useState("2026-08"); const [from, setFrom] = useState("2026-08-01"); const [to, setTo] = useState("2026-08-31");
  const period = useMemo(() => periodMode === "MONTH" ? monthPeriod(Number(periodMonth.slice(0, 4)), Number(periodMonth.slice(5, 7))) : { from, to }, [from, periodMode, periodMonth, to]);

  useEffect(() => { let active = true; void (async () => { try { const supabase = getSupabaseBrowserClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session?.user || !session.access_token) return router.replace("/auth/sign-in"); await getAdminProfile(session.user); if (active) { token.current = session.access_token; setReady(true); } } catch { if (active) setError("Accès Admin refusé."); } })(); return () => { active = false; token.current = ""; }; }, [router]);
  useEffect(() => { if (ready) void load(); }, [ready]); // eslint-disable-line react-hooks/exhaustive-deps

  async function load() {
    if (!token.current || !period.from || !period.to || period.from > period.to) { setError("Période invalide."); return; }
    const controller = new AbortController(); setLoading(true); setError(""); setUnresolved("");
    try { const result = await loadAdminBilan(token.current, buildBilanQuery(cohort, period), controller.signal); if ("code" in result) { setData(null); setUnresolved(result.requested); } else setData(result); }
    catch (cause) { setData(null); setError(cause instanceof Error ? cause.message : "Source BILAN temporairement indisponible."); }
    finally { setLoading(false); }
  }

  return <main className="min-h-screen bg-ebe-night py-8 text-white"><Container>
    <header><Link href="/admin" className="inline-flex items-center gap-2 text-sm text-accent"><ArrowLeft className="h-4 w-4"/>Retour au tableau de bord Admin</Link><div className="mt-4 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">BILAN</h1>{data ? <StatusBadge status={data.meta.status}/> : null}</div><p className="mt-2 text-sm text-muted-foreground">Lecture, agrégation et présentation uniquement — aucune écriture métier.</p></header>
    <section className="mt-8" aria-label="Zone de pilotage du bilan">
      <div className="grid gap-5 md:grid-cols-2">
        <GlassPanel className="border-accent/20 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-accent">Mois d’origine</p><label className="mt-4 block text-sm">Mois d’origine<select className={field} value={cohort} onChange={event=>setCohort(event.target.value)}>{BILAN_COHORT_OPTIONS.map(option=><option key={option.prefix} value={option.prefix}>{option.prefix} — {option.label}</option>)}</select></label><p className="mt-3 text-xs text-muted-foreground">Le préfixe du code détermine le mois d’origine du colis. La période d’analyse ne change jamais son mois d’origine.</p></GlassPanel>
        <GlassPanel className="border-primary/20 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[#AFC7FF]">Période</p><div className="mt-4 flex flex-wrap gap-2"><Button type="button" variant={periodMode==="MONTH"?"growth":"outline"} onClick={()=>setPeriodMode("MONTH")}>Mois / année</Button><Button type="button" variant={periodMode==="CUSTOM"?"growth":"outline"} onClick={()=>setPeriodMode("CUSTOM")}>Dates personnalisées</Button></div>{periodMode==="MONTH"?<label className="mt-4 block text-sm">Mois<input type="month" className={field} value={periodMonth} onChange={event=>setPeriodMonth(event.target.value)}/></label>:<div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Date de début" value={from} onChange={setFrom}/><Input label="Date de fin" value={to} onChange={setTo}/></div>}<p className="mt-3 text-xs text-muted-foreground">Utilisée uniquement pour les indicateurs de période.</p></GlassPanel>
      </div>
      <Button className="mt-5" variant="growth" onClick={()=>void load()} disabled={!ready||loading}>{loading?<LoaderCircle className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Afficher le bilan</Button>
    </section>
    {loading && !data ? <State icon={<LoaderCircle className="h-8 w-8 animate-spin text-accent"/>} title="Chargement du BILAN…"/> : null}
    {error ? <State icon={<CircleAlert className="h-8 w-8 text-amber-200"/>} title="Source indisponible" detail={error}/> : null}
    {unresolved ? <State icon={<BarChart3 className="h-8 w-8 text-muted-foreground"/>} title="COHORTE NON RÉSOLUE" detail={`Aucun mois n’a été inventé pour ${unresolved}.`}/> : null}
    {data ? <BilanView data={data}/> : null}
  </Container></main>;
}

type BilanSectionId = "activity" | "shipments" | "payments" | "direct-costs" | "expenses" | "treasury" | "results" | "quality";

function BilanView({data}:{data:BilanPayload}) {
  const [selectedSection,setSelectedSection] = useState<BilanSectionId | null>(null);
  const cards: ReadonlyArray<{id:BilanSectionId;title:string;icon:React.ReactNode;lines:string[];status?:BilanStatus;featured?:boolean}> = [
    {id:"activity",title:"Activité du mois d’origine",icon:<Activity className="h-5 w-5"/>,lines:[`Enregistré : ${kg(data.shipment.registeredCohortWeightKg)}`,`Expédié certifié : ${kg(data.shipment.certifiedShippedWeightKg)}`,`Restant : ${kg(data.shipment.remainingWeightKg)}`],status:data.shipment.status},
    {id:"shipments",title:"Expéditions du mois d’origine",icon:<PackageCheck className="h-5 w-5"/>,lines:[...agencies.map(agency=>`${agency} : ${kg(data.shipment.byAgency[agency].certifiedShippedWeightKg)}`),`Restant total : ${kg(data.shipment.remainingWeightKg)}`]},
    {id:"payments",title:"Encaissements",icon:<WalletCards className="h-5 w-5"/>,lines:[usd(data.payments.receivedAmount),`${data.payments.paymentCount} paiements`,`${data.payments.completePayments} complets · ${data.payments.partialPayments} partiels`]},
    {id:"direct-costs",title:"Charges directes",icon:<ReceiptText className="h-5 w-5"/>,lines:[`Imputées : ${usd(data.directCosts.totalAllocatedUsd)}`,`Non imputées : ${usd(data.directCosts.totalUnallocatedUsd)}`]},
    {id:"expenses",title:"Dépenses opérationnelles",icon:<BarChart3 className="h-5 w-5"/>,lines:data.periodExpenses?[`USD : ${currency(data.periodExpenses.byCurrency,"USD")}`,`FCFA : ${currency(data.periodExpenses.byCurrency,"FCFA")}`,`CDF : ${currency(data.periodExpenses.byCurrency,"CDF")}`]:["NON CALCULABLE"]},
    {id:"treasury",title:"Trésorerie",icon:<Landmark className="h-5 w-5"/>,lines:data.treasury?["TF Bénin",currencyLine(data.treasury.tfBeninByCurrency)]:["Aucune donnée disponible"]},
    {id:"results",title:"Résultat financier",icon:<TrendingUp className="h-5 w-5"/>,featured:true,lines:[`Encaissements : ${usd(data.payments.receivedAmount)}`,`Charges directes : ${usd(data.directCosts.totalAllocatedUsd)}`,`Dépenses : ${data.periodExpenses?currency(data.periodExpenses.byCurrency,"USD"):"NON CALCULABLE"}`,"Bénéfice réel : NON CALCULABLE"]},
    {id:"quality",title:"Qualité des données",icon:<ShieldAlert className="h-5 w-5"/>,lines:[`${data.dataQuality.length} anomalie(s) réelle(s)`,`${data.payments.unmatchedPayments} paiement(s) non rapproché(s)`,`${data.directCosts.unallocated.length} charge(s) non imputée(s)`],status:data.dataQuality.length?"ANOMALIE":"CERTIFIE"}
  ];
  const selectedCard = cards.find(card=>card.id===selectedSection);
  return <div className="mt-8">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Synthèse du bilan">
      {cards.map(card=><BilanSummaryCard key={card.id} {...card} selected={selectedSection===card.id} onToggle={()=>setSelectedSection(current=>current===card.id?null:card.id)}/>) }
    </div>
    {selectedSection&&selectedCard?<section id="bilan-detail-panel" aria-label={`Détails — ${selectedCard.title}`} className="mt-6 scroll-mt-6"><GlassPanel className="p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><h2 className="text-xl font-semibold">Détails — {selectedCard.title}</h2><Button type="button" variant="outline" size="sm" onClick={()=>setSelectedSection(null)}><X className="mr-2 h-4 w-4"/>Fermer</Button></div><div className="mt-6"><BilanSectionDetail section={selectedSection} data={data}/></div><p className="mt-6 text-xs text-muted-foreground">Sources lues : {data.meta.sources.join(" · ")}</p></GlassPanel></section>:null}
  </div>;
}

function BilanSummaryCard({title,icon,lines,status,featured,selected,onToggle}:{title:string;icon:React.ReactNode;lines:string[];status?:BilanStatus;featured?:boolean;selected:boolean;onToggle:()=>void}) {
  return <button type="button" aria-expanded={selected} aria-controls="bilan-detail-panel" onClick={onToggle} className={`min-h-52 rounded-xl border p-5 text-left shadow-glass transition duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${selected?"border-accent bg-accent/15 -translate-y-0.5":featured?"border-primary/50 bg-primary/10 hover:border-primary":"border-white/10 bg-white/[0.05] hover:border-white/25 hover:bg-white/[0.08]"}`}><div className="flex items-start justify-between gap-3"><span className={featured?"text-[#AFC7FF]":"text-accent"}>{icon}</span>{status?<StatusBadge status={status}/>:null}</div><h2 className="mt-4 text-base font-semibold">{title}</h2><div className="mt-3 space-y-1">{lines.slice(0,4).map(line=><p key={line} className="text-sm text-muted-foreground">{line}</p>)}</div><span className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-accent">Voir détails<ChevronRight className={`h-4 w-4 transition-transform ${selected?"rotate-90":""}`}/></span></button>;
}

function BilanSectionDetail({section,data}:{section:BilanSectionId;data:BilanPayload}) {
  if(section==="activity") return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{agencies.map(agency=>{const item=data.shipment.byAgency[agency];return <Metric key={agency} title={agency} value={kg(item.registeredWeightKg)} lines={[`Expédié : ${kg(item.certifiedShippedWeightKg)}`,`Restant : ${kg(item.remainingWeightKg)}`,formatBilanStatus(item.status)]}/>})}<Metric title="TOTAL DU MOIS D’ORIGINE" value={kg(data.activity.totalCohortWeightKg)} lines={[`Poids période : ${nullableKg(data.activity.periodRegisteredWeightKg)}`,`Écart mois d’origine / période : ${nullableKg(data.activity.cohortPeriodDifferenceKg)}`]}/></div>;
  if(section==="shipments") return <><div className="grid gap-4 md:grid-cols-3">{agencies.map(agency=>{const item=data.shipment.byAgency[agency];return <Metric key={agency} title={agency} value={kg(item.certifiedShippedWeightKg)} lines={[`Enregistré : ${kg(item.registeredWeightKg)}`,`Expédié certifié : ${kg(item.certifiedShippedWeightKg)}`,`${item.status==="CERTIFIED"?"Restant":"Solde arithmétique"} : ${kg(item.remainingWeightKg)}`,formatBilanStatus(item.status),`${item.anomalies.length} anomalie(s)`,`${item.groupages} groupages · ${item.monoCohort} mono · ${item.multiCohort} multi`]}/>})}</div>{agencies.some(agency=>data.shipment.byAgency[agency].anomalies.length)?<div className="mt-4 space-y-3">{agencies.flatMap(agency=>data.shipment.byAgency[agency].anomalies.map((issue,index)=><GlassPanel key={`${agency}-${issue.type}-${issue.sourceRawCode??issue.shipmentRawCode??index}`} className="p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge status="ANOMALIE"/><p className="font-semibold">{agency} · {issue.type.replaceAll("_"," ")}</p></div><p className="mt-2 text-sm">{[issue.sourceRawCode&&`Source ${issue.sourceRawCode}`,issue.shipmentRawCode&&`Expédition ${issue.shipmentRawCode}`,issue.sourceReference,...issue.shipmentReferences].filter(Boolean).join(" · ")}</p><p className="mt-1 text-sm text-muted-foreground">Les valeurs ambiguës restent exclues du poids expédié certifié.</p></GlassPanel>))}</div>:null}</>;
  if(section==="payments") return <div className="grid gap-4 md:grid-cols-3"><Metric title="Montant encaissé" value={usd(data.payments.receivedAmount)} lines={[`${data.payments.paymentCount} paiements`,`${data.payments.completePayments} complets · ${data.payments.partialPayments} partiels`,`${data.payments.unmatchedPayments} non rapprochés`]}/>{data.payments.historicalRevenueStatus==="CERTIFIE"?<><Metric title="Montant attendu enregistré" value={usd(data.payments.recordedExpectedAmount)}/><Metric title="Reste / taux" value={`${usd(data.payments.remainingAmount??0)} · ${percent(data.payments.collectionRate)}`}/></>:<Metric title="MONTANT ATTENDU NON CERTIFIÉ" value="Reste non calculé" lines={["Encaissements ≠ chiffre d’affaires."]}/>}</div>;
  if(section==="direct-costs") return <><div className="grid gap-4 md:grid-cols-3"><Metric title="Déclarant LSHI standard" value={usd(data.directCosts.declarantLshiUsd)} lines={["58 USD/groupage · hors DHL"]}/><Metric title="Déclarant LSHI DHL" value={usd(data.directCosts.declarantLshiDhlUsd)} lines={["2,8 USD/kg · poids officiel colonne E"]}/><Metric title="Déclarant FIH standard" value={usd(data.directCosts.declarantFihStandardUsd)}/><Metric title="Déclarant FIH DHL" value={usd(data.directCosts.declarantFihDhlUsd)}/><Metric title="Transit FIH → LSHI" value={usd(data.directCosts.transitFihLshiUsd)}/><Metric title="Expédition KLZ imputée" value={usd(data.directCosts.expeditionKlzUsd)}/><Metric title="Autres charges imputées" value={usd(data.directCosts.otherCertifiedUsd)}/><Metric title="TOTAL CHARGES DIRECTES IMPUTÉES" value={usd(data.directCosts.totalAllocatedUsd)}/><Metric title="CHARGES DIRECTES NON IMPUTÉES" value={usd(data.directCosts.totalUnallocatedUsd)} lines={[`${data.directCosts.unallocated.length} élément(s)`,"Séparées du total imputé"]}/></div><h3 className="mt-6 font-semibold">Transit FIH → LSHI</h3><div className="mt-4 grid gap-4 md:grid-cols-4"><Metric title="Condition" value="DHL + destination LSHI"/><Metric title="Nombre d’expéditions" value={String(data.transit.shipments)}/><Metric title="Poids officiel — colonne E" value={kg(data.transit.officialWeightKg)}/><Metric title="Montant total" value={usd(data.transit.amountUsd)} lines={["1,7 USD/kg"]}/></div></>;
  if(section==="expenses") return data.periodExpenses?<><CurrencyCards totals={data.periodExpenses.byCurrency}/><div className="mt-4 space-y-2">{Object.entries(data.periodExpenses.byCategoryAndCurrency).map(([category,totals])=><GlassPanel key={category} className="p-4"><p className="font-medium">{category}</p><p className="mt-1 text-sm text-muted-foreground">{currencyLine(totals)}</p></GlassPanel>)}</div></>:<Empty text="Aucune période exploitable."/>;
  if(section==="treasury") return <><h3 className="font-semibold">TF Bénin transféré à la trésorière</h3>{data.treasury?<CurrencyCards totals={data.treasury.tfBeninByCurrency}/>:<Empty text="Aucune donnée de trésorerie pour la période."/>}<p className="mt-3 text-xs text-muted-foreground">Mouvement interne de trésorerie — non inclus dans le chiffre d’affaires, les revenus, les dépenses déductibles, les charges directes ou le bénéfice.</p></>;
  if(section==="results") return <div className="grid gap-4 md:grid-cols-2"><Metric title="Chiffre d’affaires réel" value="EN ATTENTE DE CERTIFICATION"/><Metric title="Encaissements" value={usd(data.payments.receivedAmount)} lines={["Ne constituent pas le chiffre d’affaires certifié."]}/><Metric title="Charges directes nettes" value={usd(data.directCosts.totalAllocatedUsd)}/><Metric title="Dépenses opérationnelles nettes" value={data.periodExpenses?currency(data.periodExpenses.byCurrency,"USD"):"NON CALCULABLE"}/><Metric title="Charges non imputées" value={usd(data.directCosts.totalUnallocatedUsd)}/><Metric title="BÉNÉFICE RÉEL" value="NON CALCULABLE" lines={["EN ATTENTE DE CERTIFICATION"]}/><Metric title="MARGE PROVISOIRE — PÉRIMÈTRE CERTIFIÉ" value={data.results.directMargin.amountUsd===null?"NON CALCULABLE":usd(data.results.directMargin.amountUsd)} lines={[formatBilanStatus(data.results.directMargin.status)]}/></div>;
  return data.dataQuality.length?<div className="space-y-3">{data.dataQuality.map((issue,index)=><GlassPanel key={`${issue.type}-${issue.reference??index}`} className="p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge status="ANOMALIE"/><p className="font-semibold">{issue.type.replaceAll("_"," ")}</p></div><p className="mt-2 text-sm">{[issue.reference,issue.agency,issue.cohortId,issue.source].filter(Boolean).join(" · ")}</p><p className="mt-1 text-sm text-muted-foreground">{issue.impact}</p></GlassPanel>)}</div>:<Empty text="Aucune anomalie détectée pour ce périmètre."/>;
}

function Metric({title,value,lines=[]}:{title:string;value:string;lines?:string[]}) { return <GlassPanel className="p-5"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{title}</p><p className="mt-2 text-xl font-semibold">{value}</p>{lines.map(line=><p key={line} className="mt-1 text-sm text-muted-foreground">{line}</p>)}</GlassPanel>; }
function StatusBadge({status}:{status:BilanStatus}) { const label=formatBilanStatus(status); const variant=label==="CERTIFIÉ"?"growth":label==="ANOMALIE"?"premium":"muted"; return <Badge variant={variant}>{label}</Badge>; }
function CurrencyCards({totals}:{totals:Record<string,number>}) { return <div className="grid gap-4 sm:grid-cols-3">{(["USD","FCFA","CDF"] as const).map(currency=><Metric key={currency} title={currency} value={`${(totals[currency]??0).toLocaleString("fr-FR",{maximumFractionDigits:2})} ${currency}`}/>)}</div>; }
function Input({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) { return <label className="text-sm">{label}<input type="date" className={field} value={value} onChange={event=>onChange(event.target.value)}/></label>; }
function State({icon,title,detail}:{icon:React.ReactNode;title:string;detail?:string}) { return <GlassPanel className="mt-8 p-10 text-center"><div className="mx-auto w-fit">{icon}</div><h2 className="mt-3 font-semibold">{title}</h2>{detail?<p className="mt-2 text-sm text-muted-foreground">{detail}</p>:null}</GlassPanel>; }
function Empty({text}:{text:string}) { return <GlassPanel className="p-6 text-center text-sm text-muted-foreground">{text}</GlassPanel>; }
function kg(value:number){return formatWeight(value);} function nullableKg(value:number|null){return value===null?"NON CALCULABLE":kg(value);} function usd(value:number){return `${value.toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2})} USD`;} function percent(value:number|null){return value===null?"NON CALCULABLE":`${value.toLocaleString("fr-FR",{maximumFractionDigits:2})} %`;} function currency(value:Record<string,number>,code:string){return `${(value[code]??0).toLocaleString("fr-FR",{maximumFractionDigits:2})} ${code}`;} function currencyLine(value:Record<string,number>){return Object.entries(value).map(([currency,amount])=>`${amount.toLocaleString("fr-FR")} ${currency}`).join(" · ")||"Aucun montant";}
