"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, BarChart3, CircleAlert, LoaderCircle, RefreshCw } from "lucide-react";

import { Container, GlassPanel } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getAdminProfile } from "@/features/agent/auth";
import { getSupabaseBrowserClient } from "@/features/agent/supabase";
import { formatWeight } from "@/lib/format-weight";

import { loadAdminBilan } from "./bilan-client";
import { BILAN_COHORT_OPTIONS, buildBilanQuery, formatBilanStatus, monthPeriod, type BilanPayload, type BilanStatus } from "./bilan-ui";

const field = "mt-2 h-11 w-full rounded-md border border-white/15 bg-white/[0.05] px-3 text-white outline-none focus:border-accent";
const agencies = ["FIH", "LSHI", "KLZ"] as const;

export function AdminBilanPage() {
  const router = useRouter(); const token = useRef("");
  const [ready, setReady] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [data, setData] = useState<BilanPayload | null>(null); const [unresolved, setUnresolved] = useState("");
  const [cohort, setCohort] = useState("AT"); const [periodMode, setPeriodMode] = useState<"MONTH" | "CUSTOM">("MONTH");
  const [periodMonth, setPeriodMonth] = useState("2026-08"); const [from, setFrom] = useState("2026-08-01"); const [to, setTo] = useState("2026-08-31");
  const period = useMemo(() => periodMode === "MONTH" ? monthPeriod(Number(periodMonth.slice(0, 4)), Number(periodMonth.slice(5, 7))) : { from, to }, [from, periodMode, periodMonth, to]);

  useEffect(() => { let active = true; void (async () => { try { const supabase = getSupabaseBrowserClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session?.user || !session.access_token) return router.replace("/auth/sign-in"); await getAdminProfile(session.user); if (active) { token.current = session.access_token; setReady(true); } } catch { if (active) setError("Accès Admin refusé."); } })(); return () => { active = false; token.current = ""; }; }, [router]);
  useEffect(() => { if (ready) void load(); }, [ready]); // eslint-disable-line react-hooks/exhaustive-deps

  async function load() {
    if (!token.current || !period.from || !period.to || period.from > period.to) { setError("Période invalide."); return; }
    const controller = new AbortController(); setLoading(true); setError(""); setUnresolved("");
    try { const result = await loadAdminBilan(token.current, buildBilanQuery(cohort, period), controller.signal); if ("code" in result) { setData(null); setUnresolved(result.requested); } else setData(result); }
    catch (cause) { setData(null); setError(cause instanceof Error ? cause.message : "Source BILAN temporairement indisponible."); }
    finally { setLoading(false); }
  }

  return <main className="min-h-screen bg-ebe-night py-8 text-white"><Container>
    <header><Link href="/admin" className="inline-flex items-center gap-2 text-sm text-accent"><ArrowLeft className="h-4 w-4"/>Retour au tableau de bord Admin</Link><div className="mt-4 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">BILAN</h1>{data ? <StatusBadge status={data.meta.status}/> : null}</div><p className="mt-2 text-sm text-muted-foreground">Lecture, agrégation et présentation uniquement — aucune écriture métier.</p></header>
    <div className="mt-8 grid gap-5 lg:grid-cols-2">
      <GlassPanel className="border-accent/20 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-accent">A. Cohorte</p><label className="mt-4 block text-sm">Cohorte comptable<select className={field} value={cohort} onChange={event=>setCohort(event.target.value)}>{BILAN_COHORT_OPTIONS.map(option=><option key={option.prefix} value={option.prefix}>{option.prefix} — {option.label}</option>)}</select></label><p className="mt-3 text-xs text-muted-foreground">Le préfixe du code détermine la cohorte. La période ne la modifie jamais.</p></GlassPanel>
      <GlassPanel className="border-primary/20 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[#AFC7FF]">B. Période</p><div className="mt-4 flex gap-2"><Button type="button" variant={periodMode==="MONTH"?"growth":"outline"} onClick={()=>setPeriodMode("MONTH")}>Mois / année</Button><Button type="button" variant={periodMode==="CUSTOM"?"growth":"outline"} onClick={()=>setPeriodMode("CUSTOM")}>Dates personnalisées</Button></div>{periodMode==="MONTH"?<label className="mt-4 block text-sm">Mois<input type="month" className={field} value={periodMonth} onChange={event=>setPeriodMonth(event.target.value)}/></label>:<div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Date de début" value={from} onChange={setFrom}/><Input label="Date de fin" value={to} onChange={setTo}/></div>}<p className="mt-3 text-xs text-muted-foreground">Utilisée uniquement pour les indicateurs de période.</p></GlassPanel>
    </div>
    <Button className="mt-5" variant="growth" onClick={()=>void load()} disabled={!ready||loading}>{loading?<LoaderCircle className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Afficher le bilan</Button>
    {loading && !data ? <State icon={<LoaderCircle className="h-8 w-8 animate-spin text-accent"/>} title="Chargement du BILAN…"/> : null}
    {error ? <State icon={<CircleAlert className="h-8 w-8 text-amber-200"/>} title="Source indisponible" detail={error}/> : null}
    {unresolved ? <State icon={<BarChart3 className="h-8 w-8 text-muted-foreground"/>} title="COHORTE NON RÉSOLUE" detail={`Aucun mois n’a été inventé pour ${unresolved}.`}/> : null}
    {data ? <BilanView data={data}/> : null}
  </Container></main>;
}

function BilanView({data}:{data:BilanPayload}) { const cohortLabel = new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(Date.UTC(data.meta.cohortYear,data.meta.cohortMonth-1,1))); return <div className="mt-8 space-y-8">
  <GlassPanel className="p-5"><p className="font-semibold">Cohorte : <span className="capitalize">{cohortLabel}</span> — {data.meta.cohort}</p><p className="mt-2 text-sm">Période : {date(data.meta.period?.from)} → {date(data.meta.period?.to)}</p><p className="mt-2 text-sm text-muted-foreground">Statut global : <StatusBadge status={data.meta.status}/></p></GlassPanel>
  <Section title="A — Activité de cohorte"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{agencies.map(agency=><Metric key={agency} title={agency} value={kg(data.activity[agency].cohortWeightKg)} lines={[`${data.activity[agency].occurrences} occurrences`,`${data.activity[agency].uniqueIdentities} identités uniques`]}/>) }<Metric title="TOTAL COHORTE" value={kg(data.activity.totalCohortWeightKg)} lines={[`Poids période : ${nullableKg(data.activity.periodRegisteredWeightKg)}`,`Écart cohorte / période : ${nullableKg(data.activity.cohortPeriodDifferenceKg)}`]}/></div></Section>
  <Section title="B — Expédition de la cohorte"><div className="grid gap-4 md:grid-cols-3">{agencies.map(agency=>{const item=data.shipment.byAgency[agency];return <Metric key={agency} title={agency} value={kg(item.certifiedShippedWeightKg)} lines={[`Enregistré : ${kg(item.registeredWeightKg)}`,`Expédié certifié : ${kg(item.certifiedShippedWeightKg)}`,`${item.status==="CERTIFIED"?"Restant":"Solde arithmétique"} : ${kg(item.remainingWeightKg)}`,formatBilanStatus(item.status),`${item.anomalies.length} anomalie(s)`,`${item.groupages} groupages`]}/>})}</div><div className="mt-4 grid gap-4 md:grid-cols-4"><Metric title="Poids enregistré" value={kg(data.shipment.registeredCohortWeightKg)}/><Metric title="Expédié certifié" value={kg(data.shipment.certifiedShippedWeightKg)}/><Metric title="Solde arithmétique" value={kg(data.shipment.remainingWeightKg)}/><Metric title="Statut" value={formatBilanStatus(data.shipment.status)}/></div>{agencies.some(agency=>data.shipment.byAgency[agency].anomalies.length)?<div className="mt-4 space-y-3">{agencies.flatMap(agency=>data.shipment.byAgency[agency].anomalies.map((issue,index)=><GlassPanel key={`${agency}-${issue.type}-${issue.sourceRawCode??issue.shipmentRawCode??index}`} className="p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge status="ANOMALIE"/><p className="font-semibold">{agency} · {issue.type.replaceAll("_"," ")}</p></div><p className="mt-2 text-sm">{[issue.sourceRawCode&&`Source ${issue.sourceRawCode}`,issue.shipmentRawCode&&`Expédition ${issue.shipmentRawCode}`,issue.sourceReference,...issue.shipmentReferences].filter(Boolean).join(" · ")}</p><p className="mt-1 text-sm text-muted-foreground">Les valeurs ambiguës restent exclues du poids expédié certifié.</p></GlassPanel>))}</div>:null}</Section>
  <Section title="C — Encaissements"><div className="grid gap-4 md:grid-cols-3"><Metric title="Montant encaissé" value={usd(data.payments.receivedAmount)} lines={[`${data.payments.paymentCount} paiements`,`${data.payments.completePayments} complets · ${data.payments.partialPayments} partiels`,`${data.payments.unmatchedPayments} non rapprochés`]}/>{data.payments.historicalRevenueStatus==="CERTIFIE"?<><Metric title="Montant attendu enregistré" value={usd(data.payments.recordedExpectedAmount)}/><Metric title="Reste / taux" value={`${usd(data.payments.remainingAmount ?? 0)} · ${percent(data.payments.collectionRate)}`}/></>:<Metric title="MONTANT ATTENDU NON CERTIFIÉ" value="Reste non calculé" lines={["Aucun tarif courant présenté comme historique."]}/>}</div></Section>
  <Section title="D — Charges directes"><div className="grid gap-4 md:grid-cols-3"><Metric title="Déclarant LSHI standard" value={usd(data.directCosts.declarantLshiUsd)} lines={["58 USD/groupage · hors DHL"]}/><Metric title="Déclarant LSHI DHL" value={usd(data.directCosts.declarantLshiDhlUsd)} lines={["2,8 USD/kg · poids officiel colonne E"]}/><Metric title="Déclarant FIH standard" value={usd(data.directCosts.declarantFihStandardUsd)}/><Metric title="Déclarant FIH DHL" value={usd(data.directCosts.declarantFihDhlUsd)}/><Metric title="Transit FIH → LSHI" value={usd(data.directCosts.transitFihLshiUsd)}/><Metric title="Expédition KLZ imputée" value={usd(data.directCosts.expeditionKlzUsd)}/><Metric title="Autres charges imputées" value={usd(data.directCosts.otherCertifiedUsd)}/><Metric title="TOTAL CHARGES DIRECTES IMPUTÉES" value={usd(data.directCosts.totalAllocatedUsd)}/><Metric title="CHARGES DIRECTES NON IMPUTÉES" value={usd(data.directCosts.totalUnallocatedUsd)} lines={[`${data.directCosts.unallocated.length} élément(s)`,"Séparées du total imputé"]}/></div></Section>
  <Section title="Transit FIH → LSHI"><div className="grid gap-4 md:grid-cols-4"><Metric title="Condition" value="DHL + destination LSHI"/><Metric title="Nombre d’expéditions" value={String(data.transit.shipments)}/><Metric title="Poids officiel — colonne E" value={kg(data.transit.officialWeightKg)}/><Metric title="Montant total" value={usd(data.transit.amountUsd)} lines={["1,7 USD/kg"]}/></div></Section>
  <Section title="E — Dépenses opérationnelles de la période">{data.periodExpenses?<><CurrencyCards totals={data.periodExpenses.byCurrency}/><div className="mt-4 space-y-2">{Object.entries(data.periodExpenses.byCategoryAndCurrency).map(([category,totals])=><GlassPanel key={category} className="p-4"><p className="font-medium">{category}</p><p className="mt-1 text-sm text-muted-foreground">{currencyLine(totals)}</p></GlassPanel>)}</div></>:<Empty text="Aucune période exploitable."/>}</Section>
  <Section title="F — Trésorerie"><h3 className="font-semibold">TF Bénin transféré à la trésorière</h3>{data.treasury?<CurrencyCards totals={data.treasury.tfBeninByCurrency}/>:<Empty text="Aucune donnée de trésorerie pour la période."/>}<p className="mt-3 text-xs text-muted-foreground">Mouvement interne de trésorerie — non inclus dans le chiffre d’affaires ni dans les charges.</p></Section>
  <Section title="G — Résultats"><div className="grid gap-4 md:grid-cols-2"><Metric title="Résultat opérationnel de la période — USD" value={data.results.RESULTAT_OPERATIONNEL_PERIODE_USD===null?"NON CALCULABLE":usd(data.results.RESULTAT_OPERATIONNEL_PERIODE_USD)}/><Metric title="MARGE PROVISOIRE — PÉRIMÈTRE CERTIFIÉ" value={data.results.directMargin.amountUsd===null?"NON CALCULABLE":usd(data.results.directMargin.amountUsd)} lines={[formatBilanStatus(data.results.directMargin.status)]}/></div></Section>
  <Section title="H — Qualité des données">{data.dataQuality.length?<div className="space-y-3">{data.dataQuality.map((issue,index)=><GlassPanel key={`${issue.type}-${issue.reference??index}`} className="p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge status="ANOMALIE"/><p className="font-semibold">{issue.type.replaceAll("_"," ")}</p></div><p className="mt-2 text-sm">{[issue.reference,issue.agency,issue.cohortId,issue.source].filter(Boolean).join(" · ")}</p><p className="mt-1 text-sm text-muted-foreground">{issue.impact}</p></GlassPanel>)}</div>:<Empty text="Aucune anomalie détectée pour ce périmètre."/>}</Section>
  <p className="text-xs text-muted-foreground">Sources lues : {data.meta.sources.join(" · ")}</p>
  </div>; }

function Section({title,children}:{title:string;children:React.ReactNode}) { return <section><h2 className="text-xl font-semibold">{title}</h2><div className="mt-4">{children}</div></section>; }
function Metric({title,value,lines=[]}:{title:string;value:string;lines?:string[]}) { return <GlassPanel className="p-5"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{title}</p><p className="mt-2 text-xl font-semibold">{value}</p>{lines.map(line=><p key={line} className="mt-1 text-sm text-muted-foreground">{line}</p>)}</GlassPanel>; }
function StatusBadge({status}:{status:BilanStatus}) { const label=formatBilanStatus(status); const variant=label==="CERTIFIÉ"?"growth":label==="ANOMALIE"?"premium":"muted"; return <Badge variant={variant}>{label}</Badge>; }
function CurrencyCards({totals}:{totals:Record<string,number>}) { return <div className="grid gap-4 sm:grid-cols-3">{(["USD","FCFA","CDF"] as const).map(currency=><Metric key={currency} title={currency} value={`${(totals[currency]??0).toLocaleString("fr-FR",{maximumFractionDigits:2})} ${currency}`}/>)}</div>; }
function Input({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) { return <label className="text-sm">{label}<input type="date" className={field} value={value} onChange={event=>onChange(event.target.value)}/></label>; }
function State({icon,title,detail}:{icon:React.ReactNode;title:string;detail?:string}) { return <GlassPanel className="mt-8 p-10 text-center"><div className="mx-auto w-fit">{icon}</div><h2 className="mt-3 font-semibold">{title}</h2>{detail?<p className="mt-2 text-sm text-muted-foreground">{detail}</p>:null}</GlassPanel>; }
function Empty({text}:{text:string}) { return <GlassPanel className="p-6 text-center text-sm text-muted-foreground">{text}</GlassPanel>; }
function kg(value:number){return formatWeight(value);} function nullableKg(value:number|null){return value===null?"NON CALCULABLE":kg(value);} function usd(value:number){return `${value.toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2})} USD`;} function percent(value:number|null){return value===null?"NON CALCULABLE":`${value.toLocaleString("fr-FR",{maximumFractionDigits:2})} %`;} function date(value?:string){if(!value)return "NON DÉFINIE";return value.split("-").reverse().join("/");} function currencyLine(value:Record<string,number>){return Object.entries(value).map(([currency,amount])=>`${amount.toLocaleString("fr-FR")} ${currency}`).join(" · ")||"Aucun montant";}
