"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Container, GlassPanel } from "@/components/design-system";
import { Button } from "@/components/ui/button";
import { getSupabaseBrowserClient } from "@/features/agent/supabase";

type Beneficiary={beneficiary_id:string;display_name:string;agency:"COO"|"FIH"|"LSHI"|"KLZ";auth_agent_id:string|null};
type Decision={beneficiary_id:string;amount_usd:number|null;status:string;note:string|null};
export function AdminMonthlyBonusPage(){const[month,setMonth]=useState("2026-08"),[people,setPeople]=useState<Beneficiary[]>([]),[amounts,setAmounts]=useState<Record<string,string>>({}),[message,setMessage]=useState("");
async function token(){const{data:{session}}=await getSupabaseBrowserClient().auth.getSession();if(!session?.access_token)throw new Error("Session Admin requise.");return session.access_token;}
async function load(){setMessage("Chargement…");try{const response=await fetch(`/api/admin/bilan/bonuses?monthOrigin=${month}`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const body=await response.json() as {beneficiaries?:Beneficiary[];decisions?:Decision[];code?:string};if(!response.ok)throw new Error(body.code??"Source indisponible.");setPeople(body.beneficiaries??[]);setAmounts(Object.fromEntries((body.beneficiaries??[]).map(person=>[person.beneficiary_id,String((body.decisions??[]).find(item=>item.beneficiary_id===person.beneficiary_id)?.amount_usd??"")])));setMessage("");}catch(cause){setMessage(cause instanceof Error?cause.message:"Source indisponible.");}}
useEffect(()=>{void load();},[month]); // eslint-disable-line react-hooks/exhaustive-deps
async function save(certify:boolean){setMessage(certify?"Certification…":"Enregistrement…");try{const decisions=people.map(person=>({beneficiaryId:person.beneficiary_id,amountUsd:amounts[person.beneficiary_id]===""?null:Number(amounts[person.beneficiary_id])}));const response=await fetch("/api/admin/bilan/bonuses",{method:"PUT",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({monthOrigin:month,certify,decisions})});const body=await response.json() as {code?:string};if(!response.ok)throw new Error(body.code??"Enregistrement refusé.");setMessage(certify?"Prime mensuelle certifiée.":"Brouillon enregistré.");await load();}catch(cause){setMessage(cause instanceof Error?cause.message:"Enregistrement refusé.");}}
const agencies=["COO","FIH","LSHI","KLZ"] as const;const total=(agency?:string)=>people.filter(p=>!agency||p.agency===agency).reduce((sum,p)=>sum+(Number(amounts[p.beneficiary_id])||0),0);
return <main className="min-h-screen bg-ebe-night py-8 text-white"><Container><Link href="/admin/bilan" className="text-accent">← Retour au BILAN</Link><h1 className="mt-4 text-3xl font-semibold">Primes mensuelles</h1><p className="mt-2 text-sm text-muted-foreground">Configuration PDG séparée. Aucune écriture Dépenses, Caisse ou Auth.</p><GlassPanel className="mt-6 p-5"><label>Mois<input className="ml-3 rounded border border-white/15 bg-white/5 p-2" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></GlassPanel><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr><th>Agent</th><th>Agence</th><th>Compte système</th><th>Prime USD</th></tr></thead><tbody>{people.map(person=><tr key={person.beneficiary_id} className="border-t border-white/10"><td className="py-3">{person.display_name}</td><td>{person.agency}</td><td>{person.auth_agent_id?"Lié":"Sans compte"}</td><td><input aria-label={`Prime ${person.display_name}`} className="w-32 rounded border border-white/15 bg-white/5 p-2" type="number" min="0" step="0.01" value={amounts[person.beneficiary_id]??""} onChange={e=>setAmounts(current=>({...current,[person.beneficiary_id]:e.target.value}))}/></td></tr>)}</tbody></table></div><div className="mt-5 grid gap-3 sm:grid-cols-5">{agencies.map(a=><GlassPanel key={a} className="p-3"><p>{a}</p><strong>{total(a)} USD</strong></GlassPanel>)}<GlassPanel className="p-3"><p>TOTAL EEB</p><strong>{total()} USD</strong></GlassPanel></div><div className="mt-5 flex gap-3"><Button variant="outline" onClick={()=>void save(false)}>Enregistrer le brouillon</Button><Button variant="growth" onClick={()=>void save(true)}>Certifier la Prime du mois</Button></div>{message?<p role="status" className="mt-3 text-amber-100">{message}</p>:null}</Container></main>}
