import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const migration=readFileSync(new URL("./017_lshi_forwarding_departure.sql",import.meta.url),"utf8");
const rollback=readFileSync(new URL("./017_lshi_forwarding_departure.rollback.sql",import.meta.url),"utf8");
const server=readFileSync(new URL("../../../src/server/stockages-forwarding-departure.ts",import.meta.url),"utf8");
const route=readFileSync(new URL("../../../src/app/api/agent/stockages/forwardings/departure/route.ts",import.meta.url),"utf8");
const identity=readFileSync(new URL("../../../src/server/storage-parcel-identity.ts",import.meta.url),"utf8");
const list=readFileSync(new URL("../../../src/server/stockages-forwarding-in-transit.ts",import.meta.url),"utf8");
const ui=readFileSync(new URL("../../../src/features/stockages/stockages-v2-page.tsx",import.meta.url),"utf8");

function cycle(destination){const rate=destination==="KLZ"?11:13;const weight=4;const departed={originCount:9,originKg:71,destinationCount:20,destinationKg:120,status:"IN_TRANSIT",amount:weight*rate,amountPaid:0,cashEventId:null,paymentCreated:false};const arrived={...departed,destinationCount:21,destinationKg:124,status:"ARRIVAL_CONFIRMED"};const paid={...arrived,status:"READY_FOR_DELIVERY",amountPaid:arrived.amount,cashEventId:"destination-cash",paymentCreated:true};const delivered={...paid,destinationCount:20,destinationKg:120,status:"DELIVERED"};return {departed,arrived,paid,delivered};}
function dependencyGuard({migration015=true,migration016=true}={}){if(!migration015)throw new Error("MIGRATION_015_REQUIRED");if(!migration016)throw new Error("MIGRATION_016_REQUIRED");return true;}

test("garde 017 refuse 015/016 absentes avec l'erreur 015 prioritaire",()=>{assert.throws(()=>dependencyGuard({migration015:false,migration016:false}),/MIGRATION_015_REQUIRED/);});
test("garde 017 refuse 016 absente après validation de 015",()=>{assert.throws(()=>dependencyGuard({migration015:true,migration016:false}),/MIGRATION_016_REQUIRED/);});
test("garde 017 refuse un schéma 015 partiel avant toute création",()=>{assert.throws(()=>dependencyGuard({migration015:false,migration016:true}),/MIGRATION_015_REQUIRED/);const guard015=migration.indexOf("MIGRATION_015_REQUIRED");const guard016=migration.indexOf("MIGRATION_016_REQUIRED");const creation=migration.indexOf("create function public.confirm_storage_forwarding_departure");assert.ok(guard015>0&&guard015<guard016&&guard016<creation);});
test("garde 017 laisse continuer un schéma 015/016 complet",()=>{assert.equal(dependencyGuard(),true);});
test("garde 017 couvre uniquement les objets critiques réellement consommés",()=>{for(const required of ["stockage_parcels_native_identity_unique","stockage_parcels_forwarding_identity_unique","stockage_payment_forwarding_request_unique","stockage_events_native_delivery_unique","stockage_events_forwarding_delivery_unique","begin_forwarding_destination_payment","confirm_klz_forwarding_departure","record_forwarding_arrival","stockage_forwardings_financial_lifecycle_check","stockage_forwardings_status_check","stockage_forwarding_orchestrations_state_check","stockage_forwarding_events_event_type_check"])assert.match(migration,new RegExp(required));});

test("LSHI -> KLZ suit 11 USD/kg sans finance au départ",()=>{const {departed,arrived,paid,delivered}=cycle("KLZ");assert.deepEqual([departed.amount,departed.originCount,departed.originKg,departed.cashEventId,departed.paymentCreated],[44,9,71,null,false]);assert.deepEqual([arrived.destinationCount,arrived.destinationKg,arrived.status],[21,124,"ARRIVAL_CONFIRMED"]);assert.deepEqual([paid.amountPaid,paid.status],[44,"READY_FOR_DELIVERY"]);assert.deepEqual([delivered.destinationCount,delivered.destinationKg],[20,120]);});
test("LSHI -> FIH suit 13 USD/kg sans finance au départ",()=>{const {departed,arrived,paid,delivered}=cycle("FIH");assert.equal(departed.amount,52);assert.equal(departed.cashEventId,null);assert.equal(arrived.status,"ARRIVAL_CONFIRMED");assert.equal(paid.status,"READY_FOR_DELIVERY");assert.equal(delivered.status,"DELIVERED");});
test("migration 017 est additive et dérive l'origine de l'Agent",()=>{assert.match(migration,/create function public\.confirm_storage_forwarding_departure/);assert.match(migration,/v_origin:=upper\(btrim\(v_agent\.agence\)\)/);assert.match(migration,/v_origin='LSHI' and v_destination='KLZ'.*v_rate:=11/s);assert.match(migration,/v_origin='LSHI' and v_destination='FIH'.*v_rate:=13/s);assert.doesNotMatch(migration,/drop function public\.confirm_klz_forwarding_departure/);assert.match(rollback,/LSHI_FORWARDING_ALREADY_USED/);});
test("départ utilise parcel_id et forwarding_id sans paiement",()=>{assert.match(migration,/agency=v_origin and tracking_code=v_code and forwarding_id is null for update/);assert.match(migration,/jsonb_build_object\('cycle','DESTINATION_PAYMENT_AFTER_ARRIVAL'.*'parcelId',v_parcel\.parcel_id\)/s);assert.match(migration,/payment_created,payment_response,forwarding_id,state/);assert.doesNotMatch(migration,/record_cash_payment_credit/);assert.doesNotMatch(server,/paiements-agents-enregistrer-paiement|record_cash_payment_credit/);});
test("route conserve les origines KLZ et LSHI",()=>{assert.match(route,/site !== "KLZ" && auth\.identity\.site !== "LSHI"/);assert.match(server,/origin === "KLZ"/);assert.match(server,/origin === "LSHI"/);assert.match(server,/destination === "KLZ" \|\| destination === "FIH"/);assert.match(server,/confirm_storage_forwarding_departure/);});
test("alias stricts LSHI-KLZ et LSHI-FIH préservent le code",()=>{assert.match(identity,/\(KLZ\|LSHI\|FIH\)-\(KLZ\|LSHI\|FIH\)/);for(const separator of [" ","","-"])assert.match(`AT19326B${separator}LSHI-KLZ`,/^AT19326B(?: |-|)LSHI-KLZ$/);});
test("liste destination couvre KLZ FIH LSHI et reste no-store",()=>{assert.match(list,/agency !== "KLZ" && agency !== "LSHI" && agency !== "FIH"/);assert.match(list,/\.eq\("destination_agency", agency\)/);assert.match(list,/\.eq\("status", "IN_TRANSIT"\)/);assert.match(list,/cache: "no-store"/);});
test("UI conserve le départ LSHI sans retirer les arrivages normaux",()=>{assert.match(ui,/data\.account\.agency === "KLZ" \|\| data\.account\.agency === "LSHI"/);assert.match(ui,/origin === "KLZ"/);assert.match(ui,/origin === "LSHI"/);assert.match(ui,/agency: "KLZ", rate: 11/);assert.match(ui,/agency: "FIH", rate: 13/);assert.match(ui,/title="Déclarer un arrivage"/);assert.match(ui,/Acheminements en attente de réception/);});
