import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const migration=readFileSync(new URL("./018_fih_forwarding_departure.sql",import.meta.url),"utf8");
const server=readFileSync(new URL("../../../src/server/stockages-forwarding-departure.ts",import.meta.url),"utf8");
const route=readFileSync(new URL("../../../src/app/api/agent/stockages/forwardings/departure/route.ts",import.meta.url),"utf8");
const identity=readFileSync(new URL("../../../src/server/storage-parcel-identity.ts",import.meta.url),"utf8");
const list=readFileSync(new URL("../../../src/server/stockages-forwarding-in-transit.ts",import.meta.url),"utf8");
const ui=readFileSync(new URL("../../../src/features/stockages/stockages-v2-page.tsx",import.meta.url),"utf8");

function cycle(destination){const rate=destination==="LSHI"?12:13;const weight=4;const before={originCount:10,originKg:80,destinationCount:20,destinationKg:120};const departed={...before,originCount:9,originKg:76,status:"IN_TRANSIT",amountExpected:weight*rate,amountPaid:0,cashEventId:null,paymentCreated:false};const arrived={...departed,destinationCount:21,destinationKg:124,status:"ARRIVAL_CONFIRMED"};const paid={...arrived,status:"READY_FOR_DELIVERY",amountPaid:arrived.amountExpected,cashEventId:"cash-destination",paymentCreated:true};const delivered={...paid,destinationCount:20,destinationKg:120,status:"DELIVERED"};return{before,departed,arrived,paid,delivered};}

test("FIH -> LSHI suit 12 USD/kg sans finance au départ",()=>{const {departed,arrived,paid,delivered}=cycle("LSHI");assert.deepEqual([departed.amountExpected,departed.originCount,departed.originKg,departed.destinationCount,departed.destinationKg],[48,9,76,20,120]);assert.deepEqual([departed.amountPaid,departed.cashEventId,departed.paymentCreated],[0,null,false]);assert.deepEqual([arrived.destinationCount,arrived.destinationKg,arrived.status],[21,124,"ARRIVAL_CONFIRMED"]);assert.deepEqual([paid.amountPaid,paid.status],[48,"READY_FOR_DELIVERY"]);assert.deepEqual([delivered.destinationCount,delivered.destinationKg],[20,120]);});
test("FIH -> KLZ suit 13 USD/kg sans finance au départ",()=>{const {departed,arrived,paid}=cycle("KLZ");assert.equal(departed.amountExpected,52);assert.equal(departed.cashEventId,null);assert.equal(arrived.status,"ARRIVAL_CONFIRMED");assert.equal(paid.status,"READY_FOR_DELIVERY");});
test("018 est additive et conserve exactement les quatre routes existantes",()=>{assert.match(migration,/MIGRATION_017_REQUIRED/);for(const rule of ["v_origin='KLZ' and v_destination='LSHI' then v_rate:=13","v_origin='KLZ' and v_destination='FIH' then v_rate:=16","v_origin='LSHI' and v_destination='KLZ' then v_rate:=11","v_origin='LSHI' and v_destination='FIH' then v_rate:=13","v_origin='FIH' and v_destination='LSHI' then v_rate:=12","v_origin='FIH' and v_destination='KLZ' then v_rate:=13"])assert.match(migration,new RegExp(rule));assert.doesNotMatch(migration,/alter table|drop table|update public\.cash|record_cash_payment_credit/);});
test("gardes 015, 016 et 017 précèdent toute modification",()=>{const guard015=migration.indexOf("MIGRATION_015_REQUIRED");const guard016=migration.indexOf("MIGRATION_016_REQUIRED");const guard017=migration.indexOf("MIGRATION_017_REQUIRED");const replace=migration.indexOf("create or replace function public.confirm_storage_forwarding_departure");assert.ok(guard015>0&&guard015<guard016&&guard016<guard017&&guard017<replace);for(const required of ["stockage_payment_forwarding_request_unique","begin_forwarding_destination_payment","confirm_klz_forwarding_departure","record_forwarding_arrival","stockage_forwardings_financial_lifecycle_check","confirm_storage_forwarding_departure"])assert.match(migration,new RegExp(required));});
test("route, serveur et UI autorisent FIH uniquement vers LSHI/KLZ",()=>{assert.match(route,/site !== "KLZ" && auth\.identity\.site !== "LSHI" && auth\.identity\.site !== "FIH"/);assert.match(server,/ForwardingOriginAgency = "KLZ" \| "LSHI" \| "FIH"/);assert.match(server,/destination === "LSHI" \|\| destination === "KLZ"/);assert.match(ui,/data\.account\.agency === "FIH"/);assert.match(ui,/agency: "LSHI", rate: 12/);assert.match(ui,/agency: "KLZ", rate: 13/);});
test("alias FIH stricts conservent B/C/D et l'identité UUID",()=>{assert.match(identity,/\(KLZ\|LSHI\|FIH\)-\(KLZ\|LSHI\|FIH\)/);for(const suffix of ["B","C","D"])for(const separator of [" ","","-"])assert.match(`AT19326${suffix}${separator}FIH-LSHI`,new RegExp(`^AT19326${suffix}(?: |-|)FIH-LSHI$`));assert.match(migration,/where parcel_id=v_parcel\.parcel_id/);assert.match(migration,/'parcelId',v_parcel\.parcel_id/);});
test("GET IN_TRANSIT reste scellé par destination et sans cache",()=>{assert.match(list,/\.eq\("destination_agency", agency\)/);assert.match(list,/\.eq\("status", "IN_TRANSIT"\)/);assert.match(list,/cache: "no-store"/);});
test("collision natif/forwarding reste séparée",()=>{const native={parcelId:"native",trackingCode:"AT19326B",weight:5,forwardingId:null};const forwarded={parcelId:"forwarded",trackingCode:"AT19326B",weight:4,forwardingId:"fih-lshi"};assert.notEqual(native.parcelId,forwarded.parcelId);assert.notEqual(native.forwardingId,forwarded.forwardingId);assert.equal(native.trackingCode,forwarded.trackingCode);});
test("idempotence couvre départ, arrivée, paiement et remise",()=>{assert.match(migration,/creation_request_id=p_request_id for update/);assert.match(migration,/IDEMPOTENCY_CONFLICT/);assert.match(migration,/request_id=p_request_id or command_fingerprint=p_command_fingerprint/);assert.match(migration,/delete from public\.stockage_parcels where parcel_id=v_parcel\.parcel_id and version=v_parcel\.version/);});
