export const EXPENSE_CATEGORIES = [
  "Aéroport",
  "Expédition FIH",
  "Expédition LSHI",
  "Expédition KLZ",
  "Expédition LKS",
  "Déclarant",
  "Manutention",
  "Barrière",
  "Entrepôt",
  "Transport",
  "Crédit",
  "Connexion",
  "Pasteur Sera",
  "Ma Vanela",
  "Pasteur Jacques",
  "TF Bénin",
  "TF LSHI",
  "TF FIH",
  "Frais d’envoi",
  "Frais de retrait",
  "Commission clients",
  "Scotch",
  "Sacs",
  "Loyer",
  "Eau",
  "Électricité",
  "Filmage",
  "Poubelle",
  "Chauffeur",
  "Salaire",
  "Prime",
  "Dette",
  "Impression",
  "Autres"
] as const;

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];
