"use client";
import Link from "next/link"; import {useEffect,useState} from "react"; import {QrCode,ShieldAlert} from "lucide-react";
import {Container,GlassPanel} from "@/components/design-system"; import {Button} from "@/components/ui/button"; import {getSupabaseBrowserClient} from "@/features/agent/supabase"; import {correctAdminQr,loadAdminQr,revokeAdminQr,type AdminQrRecord} from "@/features/admin/admin-qr-client";
import {authenticatedRead} from "@/features/auth/authenticated-fetch";
const field="mt-2 h-11 w-full rounded-md border border-white/15 bg-ebe-night px-3 text-white";
export function AdminQrManagement(){const [access,setAccess]=useState<"checking"|"allowed"|"denied">("checking");const [selector,setSelector]=useState("");const [record,setRecord]=useState<AdminQrRecord|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [action,setAction]=useState<""|"correct"|"revoke">("");const [agency,setAgency]=useState("KLZ");const [code,setCode]=useState("");const [reason,setReason]=useState("");const [confirmed,setConfirmed]=useState(false);
useEffect(()=>{void authenticatedRead(getSupabaseBrowserClient().auth,"/api/admin/system-status").then(response=>setAccess(response.ok?"allowed":"denied")).catch(()=>setAccess("denied"));},[]);
async function search(){setBusy(true);setError("");setAction("");try{const value=await loadAdminQr(getSupabaseBrowserClient().auth,selector);setRecord(value);setAgency(value.label.agency??"KLZ");setCode(value.label.tracking_code??"");}catch(cause){setRecord(null);setError(cause instanceof Error?cause.message:"QR introuvable.");}finally{setBusy(false);}}
async function submit(){if(!record||!confirmed)return;setBusy(true);setError("");try{const common={qrId:record.label.qr_id,reason:reason.trim(),expectedVersion:record.label.version,requestId:crypto.randomUUID()};if(action==="correct")await correctAdminQr(getSupabaseBrowserClient().auth,{...common,agency,trackingCode:code.trim()});else await revokeAdminQr(getSupabaseBrowserClient().auth,common);setRecord(await loadAdminQr(getSupabaseBrowserClient().auth,record.label.qr_id));setAction("");setReason("");setConfirmed(false);}catch(cause){setError(cause instanceof Error?cause.message:"Commande refusée.");}finally{setBusy(false);}}
if(access!=="allowed")return <main className="grid min-h-screen place-items-center bg-ebe-night px-4 text-white"><GlassPanel className="max-w-md p-6 text-center"><h1 className="text-xl font-semibold">{access==="checking"?"Vérification de l’accès Admin…":"Accès Admin refusé"}</h1>{access==="denied"?<Button asChild variant="outline" className="mt-5"><Link href="/auth/sign-in">Se connecter</Link></Button>:null}</GlassPanel></main>;
return <main className="min-h-screen bg-ebe-night py-8 text-white"><Container className="max-w-5xl"><Link href="/admin" className="text-sm text-accent">← Retour à l’Admin</Link><header className="mt-5"><div className="flex items-center gap-3"><QrCode className="h-8 w-8 text-accent"/><h1 className="text-3xl font-semibold">Gestion des associations QR</h1></div><p className="mt-2 text-sm text-muted-foreground">Consultation, correction exceptionnelle et révocation auditée.</p></header><GlassPanel className="mt-7 p-6"><div className="flex gap-3"><input aria-label="Numéro QR ou qrId" value={selector} onChange={e=>setSelector(e.target.value.toUpperCase())} placeholder="013 ou EEBQR000013" className={field}/><Button type="button" variant="growth" disabled={busy||!selector.trim()} onClick={()=>void search()}>Rechercher</Button></div>{error?<p role="alert" className="mt-4 rounded-md border border-red-300/30 bg-red-400/10 p-3 text-sm">{error}</p>:null}</GlassPanel>
{record?<><GlassPanel className="mt-6 p-6"><h2 className="text-xl font-semibold">Fiche QR</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3">{Object.entries({"N° visible":record.label.display_number,qrId:record.label.qr_id,Statut:record.label.status,Agence:record.label.agency??"—","Code colis":record.label.tracking_code??"—",Version:record.label.version,"Créé le":record.label.created_at,"Créé par":record.label.created_by,"Première/dernière association":record.label.assigned_at??"—","Auteur association":record.label.assigned_by??"—","Révoqué le":record.label.revoked_at??"—","Auteur révocation":record.label.revoked_by??"—"}).map(([k,v])=><div key={k}><dt className="text-muted-foreground">{k}</dt><dd className="break-all">{String(v)}</dd></div>)}</dl><div className="mt-5 flex gap-3">{record.label.status==="ASSIGNED"?<Button type="button" variant="outline" onClick={()=>{setAction("correct");setConfirmed(false);}}>Corriger l’association</Button>:null}{record.label.status!=="REVOKED"?<Button type="button" variant="outline" onClick={()=>{setAction("revoke");setConfirmed(false);}}>Révoquer ce QR</Button>:null}</div></GlassPanel>
<GlassPanel className="mt-6 p-6"><h2 className="text-xl font-semibold">Historique d’audit append-only</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr><th>Action</th><th>Ancien état</th><th>Nouvel état</th><th>Ancienne identité</th><th>Nouvelle identité</th><th>Motif</th><th>Acteur</th><th>Date</th><th>Versions</th></tr></thead><tbody>{record.audit.map(a=><tr className="border-t border-white/10" key={a.event_id}><td className="py-3">{a.action}</td><td>{a.old_status}</td><td>{a.new_status}</td><td>{a.old_agency??"—"} + {a.old_tracking_code??"—"}</td><td>{a.new_agency??"—"} + {a.new_tracking_code??"—"}</td><td>{a.reason}</td><td>{a.actor_role} · {a.actor_id}</td><td>{a.occurred_at}</td><td>{a.version_before} → {a.version_after}</td></tr>)}</tbody></table></div></GlassPanel>
{action?<GlassPanel className="mt-6 p-6" glow="growth"><h2 className="text-xl font-semibold">{action==="correct"?"Confirmer la correction":"Confirmer la révocation exceptionnelle"}</h2>{action==="correct"?<div className="mt-4 grid gap-4 sm:grid-cols-2"><p>Association actuelle<br/><strong>{record.label.qr_id} → {record.label.agency} + {record.label.tracking_code}</strong></p><p>Nouvelle association<br/><strong>{record.label.qr_id} → {agency} + {code}</strong></p><label>Nouvelle agence<select className={field} value={agency} onChange={e=>setAgency(e.target.value)}><option>FIH</option><option>LSHI</option><option>KLZ</option></select></label><label>Nouveau code colis<input className={field} value={code} onChange={e=>setCode(e.target.value)} /></label></div>:<p className="mt-3 flex gap-2 text-amber-200"><ShieldAlert className="h-5 w-5"/>La révocation est terminale et réservée à un QR physiquement inutilisable.</p>}<label className="mt-4 block">Motif explicite obligatoire<textarea className="mt-2 w-full rounded-md border border-white/15 bg-ebe-night p-3" rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="mt-4 flex gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Je confirme avoir vérifié l’identité, le motif et la portée exceptionnelle de cette action.</span></label><div className="mt-5 flex gap-3"><Button type="button" variant="growth" disabled={busy||!confirmed||reason.trim().length<20} onClick={()=>void submit()}>{action==="correct"?"Confirmer la correction":"Confirmer la révocation"}</Button><Button type="button" variant="outline" onClick={()=>setAction("")}>Annuler</Button></div></GlassPanel>:null}</>:null}</Container></main>}
