"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Banknote, Boxes, CircleAlert, CreditCard, LoaderCircle, LogOut, ReceiptText } from "lucide-react";

import { Container, GlassPanel } from "@/components/design-system";
import { Button } from "@/components/ui/button";
import { signOutAgent } from "@/features/agent/auth";
import { getSupabaseBrowserClient } from "@/features/agent/supabase";
import { authenticatedRead, readJsonOrThrow } from "@/features/auth/authenticated-fetch";
import type { DailyAgencyReport, ReportAgency } from "@/features/daily-report/daily-report";
import { REPORT_PERIODS, type ReportPeriod } from "@/features/daily-report/report-period";
import { formatWeight } from "@/lib/format-weight";

type Payload = { from: string; to: string; agencies: DailyAgencyReport[] };
const periodLabels: Record<ReportPeriod, string> = { TODAY: "Aujourd’hui", YESTERDAY: "Hier", THIS_WEEK: "Cette semaine", LAST_WEEK: "Semaine passée", THIS_MONTH: "Ce mois", LAST_MONTH: "Mois précédent", CUSTOM: "Personnalisé" };
const inputClass = "h-11 rounded-md border border-white/15 bg-slate-950 px-3 font-medium text-white outline-none transition hover:border-accent/40 focus:border-accent focus:ring-2 focus:ring-accent/25";

export function DailyReportPage({ role }: { role: "ADMIN" | "AGENT" }) {
  const router = useRouter();
  const [data, setData] = useState<Payload | null>(null);
  const [error, setError] = useState("");
  const [agency, setAgency] = useState<ReportAgency | "ALL">("ALL");
  const [period, setPeriod] = useState<ReportPeriod>("TODAY");
  const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const [loading, setLoading] = useState(true);

  const load = useCallback(async (signal?: AbortSignal) => {
    setLoading(true); setError("");
    if (period === "CUSTOM" && (!from || !to || from > to)) { setLoading(false); return; }
    try {
      const query = new URLSearchParams();
      query.set("period", period); if (period === "CUSTOM") { query.set("from", from); query.set("to", to); }
      const response = await authenticatedRead(getSupabaseBrowserClient().auth, `/api/${role === "ADMIN" ? "admin" : "agent"}/daily-report${query.size ? `?${query}` : ""}`, { signal });
      const body = await readJsonOrThrow<Payload>(response, "Rapport indisponible.");
      setData(body); if (role === "AGENT") setAgency(body.agencies[0]?.agency ?? "ALL");
    } catch (cause) { if (!signal?.aborted) setError(cause instanceof Error ? cause.message : "Rapport indisponible."); }
    finally { if (!signal?.aborted) setLoading(false); }
  }, [from, period, role, to]);

  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const visible = useMemo(() => data?.agencies.filter((row) => agency === "ALL" || row.agency === agency) ?? [], [agency, data]);
  const title = data ? reportTitle(data.from, data.to, period) : "Rapport synthèse";
  async function logout() { await signOutAgent(); router.replace("/auth/sign-in"); }

  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,rgba(190,242,77,0.08),transparent_34%)] py-8"><Container>
    <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Link href={role === "ADMIN" ? "/admin" : "/agent"} className="inline-flex items-center gap-2 text-sm font-semibold text-accent transition hover:text-[#D9FF83]"><ArrowLeft className="h-4 w-4"/>Retour au tableau de bord</Link><h1 className="mt-3 text-3xl font-semibold uppercase tracking-tight text-white">{title}</h1><div className="mt-3 h-1 w-20 rounded-full bg-accent"/><p className="mt-3 text-sm text-muted-foreground">Lecture seule · date métier Africa/Porto-Novo</p></div><Button variant="outline" className="border-white/15 hover:border-accent/50 hover:text-accent" onClick={() => void logout()}><LogOut className="mr-2 h-4 w-4"/>Se déconnecter</Button></header>
    <GlassPanel className="mt-6 border-white/10 p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="grid gap-2 text-sm font-semibold text-white">Période<select className={inputClass} value={period} onChange={(event) => setPeriod(event.target.value as ReportPeriod)}>{REPORT_PERIODS.map((value) => <option className="bg-ebe-navy text-white" key={value} value={value}>{periodLabels[value]}</option>)}</select></label>{period === "CUSTOM" ? <><label className="grid gap-2 text-sm font-semibold text-white">Date de début<input className={inputClass} type="date" required value={from} onChange={(event) => setFrom(event.target.value)}/></label><label className="grid gap-2 text-sm font-semibold text-white">Date de fin<input className={inputClass} type="date" required min={from} value={to} onChange={(event) => setTo(event.target.value)}/></label></> : null}{role === "ADMIN" ? <label className="grid gap-2 text-sm font-semibold text-white">Agence<select value={agency} onChange={(event) => setAgency(event.target.value as ReportAgency | "ALL")} className={inputClass}><option className="bg-ebe-navy text-white" value="ALL">Toutes</option>{data?.agencies.map((row) => <option className="bg-ebe-navy text-white" key={row.agency}>{row.agency}</option>)}</select></label> : null}</div><Button variant="growth" className="mt-4" disabled={loading || (period === "CUSTOM" && (!from || !to || from > to))} onClick={() => void load()}>{loading ? "Actualisation…" : "Appliquer les filtres"}</Button>{period === "CUSTOM" && (!from || !to || from > to) ? <p role="alert" className="mt-3 text-sm text-amber-200">Le début et la fin sont obligatoires, avec une date de début antérieure ou égale à la fin.</p> : null}</GlassPanel>
    {error ? <State error={error}/> : loading && !data ? <State/> : <>{visible.map((report) => <AgencySection key={report.agency} report={report} role={role} from={data!.from} to={data!.to} onNoteAdded={() => void load()}/>)}{role === "ADMIN" && agency === "ALL" && data ? <GlobalSummary reports={data.agencies}/> : null}</>}
  </Container></main>;
}

function AgencySection({ report, role, from, to, onNoteAdded }: { report: DailyAgencyReport; role: "ADMIN" | "AGENT"; from: string; to: string; onNoteAdded: () => void }) { return <section className="mt-8"><h2 className="border-b border-white/10 pb-3 text-2xl font-semibold text-white"><span className="mr-2 text-accent">●</span>Agence : {report.agency}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={CreditCard} title="Encaissements" value={usd(report.paymentsTotal)} detail={`${report.paymentCount} opération(s)`}/><Card icon={ReceiptText} title="Dépenses" value={currencyTotals(report.expensesByCurrency)} detail={`${report.expenseCount} opération(s)`}/><Card icon={Boxes} title="Arrivages" value={formatWeight(report.arrivalWeightKg)} detail={`${report.arrivalCount} colis`}/><Card icon={Boxes} title="Sorties" value={formatWeight(report.departureWeightKg)} detail={`${report.departureCount} colis`}/></div>
  {report.cash ? <GlassPanel className="mt-4 border-white/10 p-5"><h3 className="text-lg font-semibold text-white">Caisse {report.agency} — <span className="rounded-full border border-accent/30 bg-accent/10 px-2 py-1 text-xs text-accent">{report.cash.status}</span></h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Mini label="Solde au début" value={usd(report.cash.openingBalance)}/><Mini label="Encaissements" value={`+${usd(report.cash.paymentsTotal)}`}/><Mini label="Dépenses" value={`-${usd(report.cash.expensesTotal)}`}/><Mini label="Ajustements" value={signedUsd(report.cash.correctionsNet)}/><Mini label="Solde à la fin" value={usd(report.cash.currentBalance)}/></div><Detail title="Ajustements Admin audités" rows={report.adjustments.map((row) => `${row.direction === "CREDIT" ? "+" : "-"}${usd(row.amount)} — ${row.reason} — ${row.admin} — ${dateTime(row.occurredAt)}`)} sourceHref={role === "ADMIN" ? "/admin/caisse" : undefined}/></GlassPanel> : <GlassPanel className="mt-4 border-white/10 p-5"><h3 className="text-lg font-semibold text-white">Recettes COO hors caisse</h3><p className="mt-2 text-sm text-muted-foreground">COO ne possède aucun solde de Caisse.</p></GlassPanel>}
  {report.storage ? <GlassPanel className="mt-4 border-white/10 p-5"><h3 className="text-lg font-semibold text-white">Stockage {report.agency}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Mini label="Stock au début" value={`${report.storage.openingParcels} colis · ${formatWeight(report.storage.openingWeightKg)}`}/><Mini label="Arrivages" value={`+${report.storage.arrivalsParcels} colis · +${formatWeight(report.storage.arrivalsWeightKg)}`}/><Mini label="Sorties" value={`-${report.storage.departuresParcels} colis · -${formatWeight(report.storage.departuresWeightKg)}`}/><Mini label="Stock à la fin" value={`${report.storage.closingParcels} colis · ${formatWeight(report.storage.closingWeightKg)}`}/></div></GlassPanel> : null}
  <div className="mt-4 grid gap-4 lg:grid-cols-2"><Detail title="Détail Agents" rows={report.byAgent.map((row) => `${row.name} — ${row.count} encaissement(s) — ${usd(row.amount)}`)} sourceHref={role === "ADMIN" ? "/admin/encaissements" : undefined}/><Detail title="Modes de paiement" rows={report.paymentModes.map((row) => `${row.name} — ${row.count} opération(s) — ${usd(row.amount)}`)}/><Detail title="Détail Dépenses" rows={report.expenses.map((row) => `${row.category} — ${row.amount} ${row.currency} — ${row.agent || "—"} — ${row.description || row.reference || "—"}`)} sourceHref={role === "ADMIN" ? "/admin/depenses" : undefined}/><Detail title="Détail Arrivages" rows={report.arrivals.map((row) => `${row.code} — ${formatWeight(row.weightKg)} — ${row.actor} — ${dateTime(row.occurredAt)}`)} sourceHref={role === "ADMIN" ? "/admin/stockages" : undefined}/><Detail title="Détail Sorties" rows={report.departures.map((row) => `${row.code} — ${formatWeight(row.weightKg)} — ${row.actor} — ${dateTime(row.occurredAt)}`)} sourceHref={role === "ADMIN" ? "/admin/stockages" : undefined}/><GlassPanel className="border-white/10 p-5"><h3 className="font-semibold text-white"><span className="mr-2 text-accent">●</span>Total consolidé agence</h3><p className="mt-3 text-sm text-white">{report.paymentCount} encaissement(s) · {usd(report.paymentsTotal)} · {report.expenseCount} dépense(s) · {report.arrivalCount} arrivée(s) · {report.departureCount} sortie(s) · {report.activeAgents} Agent(s) actif(s)</p></GlassPanel><Detail title="Notes administratives" rows={report.notes.map((row) => `${row.content} — ${row.admin} — ${dateTime(row.occurredAt)}${row.visibleToAgents ? " — visible aux Agents" : ""}`)}/>{role === "ADMIN" && report.agency !== "COO" ? <AdminNoteForm agency={report.agency} from={from} to={to} onAdded={onNoteAdded}/> : null}</div></section>; }

function AdminNoteForm({ agency, from, to, onAdded }: { agency: Exclude<ReportAgency, "COO">; from: string; to: string; onAdded: () => void }) { const [content,setContent]=useState(""); const [visible,setVisible]=useState(false); const [feedback,setFeedback]=useState(""); async function submit(event:React.FormEvent){event.preventDefault();setFeedback("Enregistrement…");const {data:{session}}=await getSupabaseBrowserClient().auth.getSession();const response=await fetch("/api/admin/daily-report/note",{method:"POST",headers:{Authorization:`Bearer ${session?.access_token ?? ""}`,"Content-Type":"application/json"},body:JSON.stringify({agency,from,to,content,visibleToAgents:visible,confirmationFinal:true})});const body=await response.json().catch(()=>null) as {message?:string}|null;if(!response.ok){setFeedback(body?.message??"Note refusée.");return;}setContent("");setVisible(false);setFeedback("Note auditée enregistrée.");onAdded();} return <GlassPanel className="border-white/10 p-5"><h3 className="font-semibold text-white"><span className="mr-2 text-accent">●</span>Ajouter une note administrative</h3><p className="mt-2 text-xs text-muted-foreground">La note ne modifie aucun calcul et est conservée dans l’Audit immutable.</p><form className="mt-3 grid gap-3" onSubmit={submit}><textarea className="min-h-24 rounded-md border border-white/15 bg-slate-950 p-3 outline-none transition focus:border-accent focus:ring-2 focus:ring-accent/25" minLength={3} maxLength={1000} required value={content} onChange={(event)=>setContent(event.target.value)} placeholder="Observation administrative"/><label className="flex gap-2 text-sm text-slate-200"><input className="accent-lime-400" type="checkbox" checked={visible} onChange={(event)=>setVisible(event.target.checked)}/>Visible aux Agents de {agency}</label><Button variant="growth" type="submit">Confirmer et auditer la note</Button>{feedback?<p role="status" className="text-sm text-amber-100">{feedback}</p>:null}</form></GlassPanel>; }
function GlobalSummary({ reports }: { reports: DailyAgencyReport[] }) { const payments = reports.reduce((sum,row)=>sum+row.paymentsTotal,0); const expenses = reports.reduce<Record<string,number>>((totals,row)=>{for(const [currency,value] of Object.entries(row.expensesByCurrency)) totals[currency]=(totals[currency]??0)+value;return totals;},{}); const arrivals = reports.reduce((sum,row)=>sum+row.arrivalCount,0); const arrivalKg=reports.reduce((sum,row)=>sum+row.arrivalWeightKg,0); const departures=reports.reduce((sum,row)=>sum+row.departureCount,0); const departureKg=reports.reduce((sum,row)=>sum+row.departureWeightKg,0); return <GlassPanel className="mt-8 border-white/10 p-6"><h2 className="text-xl font-semibold text-white"><span className="mr-2 text-accent">●</span>Synthèse générale de la période</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{reports.map((row)=><Mini key={row.agency} label={`Encaissements ${row.agency}`} value={usd(row.paymentsTotal)}/>) }{reports.map((row)=><Mini key={`expenses-${row.agency}`} label={`Dépenses ${row.agency}`} value={currencyTotals(row.expensesByCurrency)}/>) }<Mini label="Total général encaissé" value={usd(payments)}/><Mini label="Total général dépenses" value={currencyTotals(expenses)}/><Mini label="Arrivages toutes agences" value={`${arrivals} colis · ${formatWeight(arrivalKg)}`}/><Mini label="Sorties toutes agences" value={`${departures} colis · ${formatWeight(departureKg)}`}/></div><p className="mt-3 text-xs text-muted-foreground">COO reste consolidé comme recettes hors caisse, jamais comme une Caisse.</p></GlassPanel>; }
function Card({icon:Icon,title,value,detail}:{icon:typeof Banknote;title:string;value:string;detail:string}) { return <GlassPanel className="border-white/10 p-5"><div className="grid h-10 w-10 place-items-center rounded-lg border border-accent/30 bg-accent/10 text-accent"><Icon className="h-5 w-5"/></div><p className="mt-3 text-sm font-semibold text-white">{title}</p><p className="mt-1 text-xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></GlassPanel>; }
function Detail({title,rows,sourceHref}:{title:string;rows:string[];sourceHref?:string}) { return <GlassPanel className="border-white/10 p-5"><h3 className="font-semibold text-white"><span className="mr-2 text-accent">●</span>{title}</h3>{sourceHref?<Link href={sourceHref} className="mt-1 inline-block text-xs font-semibold text-accent underline decoration-accent/40 underline-offset-4 transition hover:text-[#D9FF83]">Voir / corriger l’opération source</Link>:null}{rows.length?<ul className="mt-3 space-y-2 text-sm">{rows.map((row,index)=><li key={`${index}-${row}`} className="rounded border border-white/10 bg-white/[0.025] p-3 text-slate-100">{row}</li>)}</ul>:<p className="mt-3 text-sm text-muted-foreground">Aucune opération sur la période.</p>}</GlassPanel>; }
function Mini({label,value}:{label:string;value:string}) { return <div className="rounded border border-white/10 bg-white/[0.025] p-3"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 font-semibold text-white">{value}</p></div>; }
function State({error}:{error?:string}) { return <GlassPanel className="mt-8 p-8 text-center">{error?<CircleAlert className="mx-auto h-7 w-7 text-red-200"/>:<LoaderCircle className="mx-auto h-7 w-7 animate-spin text-accent"/>}<p className="mt-3">{error??"Chargement du rapport…"}</p></GlassPanel>; }
function reportTitle(from:string,to:string,preset:ReportPeriod){const start=formatDate(from),end=formatDate(to);if(from===to)return `Rapport synthèse du ${start}`;if(preset==="THIS_WEEK"||preset==="LAST_WEEK")return `Rapport synthèse — semaine du ${start} au ${end}`;return `Rapport synthèse du ${start} au ${end}`;}
function formatDate(value:string){return new Intl.DateTimeFormat("fr-FR",{timeZone:"Africa/Porto-Novo"}).format(new Date(`${value}T12:00:00Z`));}
function usd(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"USD"}).format(value);} function signedUsd(value:number){return `${value>=0?"+":""}${usd(value)}`;} function currencyTotals(values:Readonly<Record<string,number>>){const rows=Object.entries(values);return rows.length?rows.map(([currency,value])=>`${value} ${currency}`).join(" · "):"0";} function dateTime(value:string){if(!value)return "—";return new Intl.DateTimeFormat("fr-FR",{timeZone:"Africa/Porto-Novo",dateStyle:"short",timeStyle:"short"}).format(new Date(value));}
