"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Banknote, Boxes, CircleAlert, CreditCard, LoaderCircle, LogOut, ReceiptText } from "lucide-react";

import { Container, GlassPanel } from "@/components/design-system";
import { Button } from "@/components/ui/button";
import { signOutAgent } from "@/features/agent/auth";
import { getSupabaseBrowserClient } from "@/features/agent/supabase";
import type { DailyAgencyReport, ReportAgency } from "@/features/daily-report/daily-report";
import { formatWeight } from "@/lib/format-weight";

type Payload = { businessDate: string; agencies: DailyAgencyReport[] };

export function DailyReportPage({ role }: { role: "ADMIN" | "AGENT" }) {
  const router = useRouter();
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [agency, setAgency] = useState<ReportAgency | "ALL">("ALL");
  useEffect(() => { let active = true; void (async () => { try { const { data: { session } } = await getSupabaseBrowserClient().auth.getSession(); if (!session?.access_token) return router.replace("/auth/sign-in"); const response = await fetch(`/api/${role === "ADMIN" ? "admin" : "agent"}/daily-report`, { headers: { Authorization: `Bearer ${session.access_token}` }, cache: "no-store" }); const body = await response.json() as Payload & { message?: string }; if (!response.ok) throw new Error(body.message || "Rapport indisponible."); if (active) { setData(body); if (role === "AGENT") setAgency(body.agencies[0]?.agency ?? "ALL"); } } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : "Rapport indisponible."); } })(); return () => { active = false; }; }, [role, router]);
  const visible = useMemo(() => data?.agencies.filter((row) => agency === "ALL" || row.agency === agency) ?? [], [agency, data]);
  const dateLabel = data ? new Intl.DateTimeFormat("fr-FR", { timeZone: "Africa/Porto-Novo" }).format(new Date(`${data.businessDate}T12:00:00Z`)) : "…";
  async function logout() { await signOutAgent(); router.replace("/auth/sign-in"); }
  return <main className="min-h-screen py-8"><Container><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Link href={role === "ADMIN" ? "/admin" : "/agent"} className="inline-flex items-center gap-2 text-sm text-accent"><ArrowLeft className="h-4 w-4"/>Retour au tableau de bord</Link><h1 className="mt-3 text-3xl font-semibold uppercase">Rapport synthèse du {dateLabel}</h1><p className="mt-2 text-sm text-muted-foreground">Lecture seule · date métier Africa/Porto-Novo</p></div><Button variant="outline" onClick={() => void logout()}><LogOut className="mr-2 h-4 w-4"/>Se déconnecter</Button></header>
    {role === "ADMIN" && data ? <GlassPanel className="mt-6 p-5"><label className="text-sm">Agence<select value={agency} onChange={(event) => setAgency(event.target.value as ReportAgency | "ALL")} className="ml-3 rounded-md border border-white/15 bg-slate-950 px-3 py-2"><option value="ALL">Toutes</option>{data.agencies.map((row) => <option key={row.agency}>{row.agency}</option>)}</select></label></GlassPanel> : null}
    {error ? <State error={error}/> : !data ? <State/> : <>{visible.map((report) => <AgencySection key={report.agency} report={report}/>)}{role === "ADMIN" && agency === "ALL" ? <GlobalSummary reports={data.agencies}/> : null}</>}
  </Container></main>;
}

function AgencySection({ report }: { report: DailyAgencyReport }) { return <section className="mt-8"><h2 className="text-2xl font-semibold">Agence : {report.agency}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={CreditCard} title="Encaissements" value={usd(report.paymentsTotal)} detail={`${report.paymentCount} opération(s)`}/><Card icon={ReceiptText} title="Dépenses" value={currencyTotals(report.expensesByCurrency)} detail={`${report.expenseCount} opération(s)`}/><Card icon={Boxes} title="Arrivages" value={formatWeight(report.arrivalWeightKg)} detail={`${report.arrivalCount} colis`}/><Card icon={Boxes} title="Sorties" value={formatWeight(report.departureWeightKg)} detail={`${report.departureCount} colis`}/></div>
  {report.cash ? <GlassPanel className="mt-4 p-5"><h3 className="font-semibold">Caisse {report.agency} — {report.cash.status}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Mini label="Solde précédent" value={usd(report.cash.openingBalance)}/><Mini label="Encaissements" value={`+${usd(report.cash.paymentsTotal)}`}/><Mini label="Dépenses" value={`-${usd(report.cash.expensesTotal)}`}/><Mini label="Ajustements" value={signedUsd(report.cash.correctionsNet)}/><Mini label="Solde actuel" value={usd(report.cash.currentBalance)}/></div></GlassPanel> : <GlassPanel className="mt-4 p-5"><h3 className="font-semibold">Recettes COO hors caisse</h3><p className="mt-2 text-sm text-muted-foreground">COO ne possède aucun solde de Caisse.</p></GlassPanel>}
  <div className="mt-4 grid gap-4 lg:grid-cols-2"><Detail title="Détail Agents" rows={report.byAgent.map((row) => `${row.name} — ${row.count} encaissement(s) — ${usd(row.amount)}`)}/><Detail title="Modes de paiement" rows={report.paymentModes.map((row) => `${row.name} — ${row.count} opération(s) — ${usd(row.amount)}`)}/><Detail title="Détail Dépenses" rows={report.expenses.map((row) => `${row.category} — ${row.amount} ${row.currency} — ${row.agent || "—"} — ${row.description || row.reference || "—"}`)}/><Detail title="Détail Arrivages" rows={report.arrivals.map((row) => `${row.code} — ${formatWeight(row.weightKg)} — ${row.actor} — ${dateTime(row.occurredAt)}`)}/><Detail title="Détail Sorties" rows={report.departures.map((row) => `${row.code} — ${formatWeight(row.weightKg)} — ${row.actor} — ${dateTime(row.occurredAt)}`)}/><GlassPanel className="p-5"><h3 className="font-semibold">Total consolidé agence</h3><p className="mt-3 text-sm">{report.paymentCount} encaissement(s) · {usd(report.paymentsTotal)} · {report.expenseCount} dépense(s) · {report.arrivalCount} arrivée(s) · {report.departureCount} sortie(s) · {report.activeAgents} Agent(s) actif(s)</p></GlassPanel></div></section>; }

function GlobalSummary({ reports }: { reports: DailyAgencyReport[] }) { const payments = reports.reduce((sum,row)=>sum+row.paymentsTotal,0); const expenses = reports.reduce<Record<string,number>>((totals,row)=>{for(const [currency,value] of Object.entries(row.expensesByCurrency)) totals[currency]=(totals[currency]??0)+value;return totals;},{}); const arrivals = reports.reduce((sum,row)=>sum+row.arrivalCount,0); const arrivalKg=reports.reduce((sum,row)=>sum+row.arrivalWeightKg,0); const departures=reports.reduce((sum,row)=>sum+row.departureCount,0); const departureKg=reports.reduce((sum,row)=>sum+row.departureWeightKg,0); return <GlassPanel className="mt-8 p-6"><h2 className="text-xl font-semibold">Synthèse générale du jour</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{reports.map((row)=><Mini key={row.agency} label={`Encaissements ${row.agency}`} value={usd(row.paymentsTotal)}/>) }{reports.map((row)=><Mini key={`expenses-${row.agency}`} label={`Dépenses ${row.agency}`} value={currencyTotals(row.expensesByCurrency)}/>) }<Mini label="Total général encaissé" value={usd(payments)}/><Mini label="Total général dépenses" value={currencyTotals(expenses)}/><Mini label="Arrivages toutes agences" value={`${arrivals} colis · ${formatWeight(arrivalKg)}`}/><Mini label="Sorties toutes agences" value={`${departures} colis · ${formatWeight(departureKg)}`}/></div><p className="mt-3 text-xs text-muted-foreground">COO reste consolidé comme recettes hors caisse, jamais comme une Caisse.</p></GlassPanel>; }
function Card({icon:Icon,title,value,detail}:{icon:typeof Banknote;title:string;value:string;detail:string}) { return <GlassPanel className="p-5"><Icon className="h-5 w-5 text-accent"/><p className="mt-3 text-sm text-muted-foreground">{title}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></GlassPanel>; }
function Detail({title,rows}:{title:string;rows:string[]}) { return <GlassPanel className="p-5"><h3 className="font-semibold">{title}</h3>{rows.length?<ul className="mt-3 space-y-2 text-sm">{rows.map((row,index)=><li key={`${index}-${row}`} className="rounded border border-white/10 p-3">{row}</li>)}</ul>:<p className="mt-3 text-sm text-muted-foreground">Aucune opération aujourd’hui.</p>}</GlassPanel>; }
function Mini({label,value}:{label:string;value:string}) { return <div className="rounded border border-white/10 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function State({error}:{error?:string}) { return <GlassPanel className="mt-8 p-8 text-center">{error?<CircleAlert className="mx-auto h-7 w-7 text-red-200"/>:<LoaderCircle className="mx-auto h-7 w-7 animate-spin text-accent"/>}<p className="mt-3">{error??"Chargement du rapport…"}</p></GlassPanel>; }
function usd(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"USD"}).format(value);} function signedUsd(value:number){return `${value>=0?"+":""}${usd(value)}`;} function currencyTotals(values:Readonly<Record<string,number>>){const rows=Object.entries(values);return rows.length?rows.map(([currency,value])=>`${value} ${currency}`).join(" · "):"0";} function dateTime(value:string){if(!value)return "—";return new Intl.DateTimeFormat("fr-FR",{timeZone:"Africa/Porto-Novo",dateStyle:"short",timeStyle:"short"}).format(new Date(value));}
