"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { GlassPanel } from "@/components/design-system";
import { Button } from "@/components/ui/button";
import { getSupabaseBrowserClient } from "@/features/agent/supabase";
import type { DailyAgencyReport, ReportAgency } from "@/features/daily-report/daily-report";
import { REPORT_PERIODS, type ReportPeriod } from "@/features/daily-report/report-period";

type Payload = { from: string; to: string; agencies: DailyAgencyReport[] };
const labels: Record<ReportPeriod,string> = { TODAY:"Aujourd’hui",YESTERDAY:"Hier",THIS_WEEK:"Cette semaine",LAST_WEEK:"Semaine passée",THIS_MONTH:"Ce mois",LAST_MONTH:"Mois précédent",CUSTOM:"Personnalisé" };
const field = "mt-2 h-11 w-full rounded-md border border-white/15 bg-slate-950 px-3 text-white outline-none focus:border-accent";

export function CashPeriodConsultation() {
  const [period,setPeriod]=useState<ReportPeriod>("TODAY"); const [agency,setAgency]=useState<ReportAgency|"ALL">("ALL");
  const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const {data:{session}}=await getSupabaseBrowserClient().auth.getSession();if(!session?.access_token)throw new Error("Session Admin expirée.");const query=new URLSearchParams({period});if(period==="CUSTOM"){query.set("from",from);query.set("to",to);}const response=await fetch(`/api/admin/daily-report?${query}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const body=await response.json() as Payload&{message?:string};if(!response.ok)throw new Error(body.message??"Consultation indisponible.");setData(body);}catch(cause){setError(cause instanceof Error?cause.message:"Consultation indisponible.");}finally{setLoading(false);}},[from,period,to]);
  useEffect(()=>{void load();},[load]);
  const rows=useMemo(()=>data?.agencies.filter(row=>agency==="ALL"||row.agency===agency)??[],[agency,data]);
  const total=rows.reduce((sum,row)=>sum+row.paymentsTotal,0); const count=rows.reduce((sum,row)=>sum+row.paymentCount,0);
  return <section className="mt-8"><h2 className="text-2xl font-semibold">Consultation par période</h2><GlassPanel className="mt-5 p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-semibold">Agence<select className={field} value={agency} onChange={event=>setAgency(event.target.value as ReportAgency|"ALL")}><option value="ALL">Toutes les agences</option><option>FIH</option><option>LSHI</option><option>KLZ</option><option>COO</option></select></label><label className="text-sm font-semibold">Période<select className={field} value={period} onChange={event=>setPeriod(event.target.value as ReportPeriod)}>{REPORT_PERIODS.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label>{period==="CUSTOM"?<><label className="text-sm font-semibold">Date début<input className={field} type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label className="text-sm font-semibold">Date fin<input className={field} type="date" min={from} value={to} onChange={event=>setTo(event.target.value)}/></label></>:null}</div><Button variant="growth" className="mt-4" disabled={loading||(period==="CUSTOM"&&(!from||!to||from>to))} onClick={()=>void load()}>{loading?"Chargement…":"Appliquer les filtres"}</Button>{error?<p role="alert" className="mt-3 text-sm text-red-200">{error}</p>:null}</GlassPanel>{data?<><div className="mt-5 grid gap-4 xl:grid-cols-2">{rows.map(row=><GlassPanel key={row.agency} className="p-5"><h3 className="text-lg font-semibold">{row.agency==="COO"?"Recettes COO hors caisse":`Caisse ${row.agency}`}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Metric label="Nombre d’encaissements" value={String(row.paymentCount)}/><Metric label="Montant encaissé" value={usd(row.paymentsTotal)}/><Metric label="Dépenses" value={Object.entries(row.expensesByCurrency).map(([currency,value])=>`${value} ${currency}`).join(" · ")||"0"}/>{row.cash?<><Metric label="Corrections Admin" value={signed(row.cash.correctionsNet)}/><Metric label="Solde début" value={usd(row.cash.openingBalance)}/><Metric label="Solde fin" value={usd(row.cash.currentBalance)}/></>:<Metric label="Caisse" value="Hors caisse"/>}</div></GlassPanel>)}</div>{agency==="ALL"?<GlassPanel className="mt-5 p-5"><h3 className="font-semibold">Total consolidé des Encaissements</h3><p className="mt-2 text-xl font-semibold">{count} encaissement(s) · {usd(total)}</p><p className="mt-2 text-xs text-muted-foreground">COO est inclus uniquement dans les recettes consolidées, jamais dans un solde de Caisse.</p></GlassPanel>:null}</>:null}</section>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded border border-white/10 bg-white/[0.03] p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>;}
function usd(value:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"USD"}).format(value);} function signed(value:number){return `${value>=0?"+":""}${usd(value)}`;}
