import { NextResponse } from "next/server";
import { authorizeAgentRequest } from "@/server/agent-authorization";
import { recordForwardingArrival } from "@/server/stockages-forwarding";
import { StockagesV2Error } from "@/server/stockages-v2";
import { recordInternalNotification } from "@/server/internal-notifications";

export const dynamic = "force-dynamic"; export const runtime = "nodejs";
export async function POST(request: Request) { try { const auth=await authorizeAgentRequest(request); if(!auth.authorized)return fail("ACCESS_DENIED",auth.status); const body=await request.json() as Record<string,unknown>; if(Object.keys(body).some((key)=>!["forwardingReference","requestId","confirmed"].includes(key))||body.confirmed!==true)return fail("INVALID_FORWARDING_ARRIVAL",400); const result=await recordForwardingArrival({forwardingReference:String(body.forwardingReference??""),requestId:String(body.requestId??""),actorId:auth.identity.userId,actorAgency:auth.identity.site}); if(!result.replayed){const agency=auth.identity.site as "FIH"|"LSHI"|"KLZ";const eventId=result.eventId??String(body.requestId);const reference=String(body.forwardingReference??"").trim().toUpperCase();const summary=`1 colis / ${result.weightKg} kg`;await Promise.allSettled([recordInternalNotification({eventKey:`stock_arrival:${eventId}:admin`,agency,audience:"ADMIN",type:"STORAGE_ARRIVAL",title:"Arrivage Stockage enregistré",message:`${agency} a enregistré un nouvel arrivage : ${summary}. Référence : ${reference}.`,actorUserId:auth.identity.userId,actorName:auth.identity.nom}),recordInternalNotification({eventKey:`stock_arrival:${eventId}:coo`,agency:"COO",audience:"AGENT",type:"STORAGE_ARRIVAL",title:`Arrivage confirmé à ${agency}`,message:`${agency} a confirmé la réception physique de ${summary}. Référence : ${reference}.`,actorUserId:auth.identity.userId,actorName:auth.identity.nom})]);} return NextResponse.json({state:"SUCCESS",...result},{status:result.replayed?200:201}); } catch(cause){return cause instanceof StockagesV2Error?fail(cause.code,cause.status):fail("FORWARDING_SERVICE_UNAVAILABLE",503);} }
function fail(code:string,status:number){return NextResponse.json({state:"ERROR",code,message:code==="WRONG_AGENCY"?"Cet acheminement n’est pas destiné à votre agence.":"L’arrivage de l’acheminement a été refusé."},{status});}
